import UIKit

public enum Icon {
    public enum Size: String, CaseIterable {
        case tiny = "--tiny"
        case small = "--small"
        case medium = "--medium"

        public var dimension: CGFloat {
            switch self {
            case .tiny:
                return 14
            case .small:
                return 18
            case .medium:
                return 28
            }
        }
    }

    /// *Must* be called before attempting to reference any icons.
    public static func register(bundle: Bundle) {
        Self.bundle = bundle
    }

    public enum Name: String, CaseIterable {
        case contentActionsAddMedium = "contentActions_add--medium"
        case contentActionsAddSmall = "contentActions_add--small"
        case contentActionsArchiveMedium = "contentActions_archive--medium"
        case contentActionsArchiveSmall = "contentActions_archive--small"
        case contentActionsArchiveFilledSmall = "contentActions_archive-filled--small"
        case contentActionsAttachMedium = "contentActions_attach--medium"
        case contentActionsAttachSmall = "contentActions_attach--small"
        case contentActionsAttachTiny = "contentActions_attach--tiny"
        case contentActionsAudioMedium = "contentActions_audio--medium"
        case contentActionsAudioSmall = "contentActions_audio--small"
        case contentActionsBudgetMedium = "contentActions_budget--medium"
        case contentActionsBudgetSmall = "contentActions_budget--small"
        case contentActionsCheckMedium = "contentActions_check--medium"
        case contentActionsCheckSmall = "contentActions_check--small"
        case contentActionsCheckTiny = "contentActions_check--tiny"
        case contentActionsCopyLinkMedium = "contentActions_copy-link--medium"
        case contentActionsCopyLinkSmall = "contentActions_copy-link--small"
        case contentActionsEditMedium = "contentActions_edit--medium"
        case contentActionsEditSmall = "contentActions_edit--small"
        case contentActionsExportMedium = "contentActions_export--medium"
        case contentActionsExportSmall = "contentActions_export--small"
        case contentActionsFilterMedium = "contentActions_filter--medium"
        case contentActionsFilterSmall = "contentActions_filter--small"
        case contentActionsFlagMedium = "contentActions_flag--medium"
        case contentActionsFlagSmall = "contentActions_flag--small"
        case contentActionsFolderMedium = "contentActions_folder--medium"
        case contentActionsFolderSmall = "contentActions_folder--small"
        case contentActionsGestureMedium = "contentActions_gesture--medium"
        case contentActionsImageMedium = "contentActions_image--medium"
        case contentActionsImageSmall = "contentActions_image--small"
        case contentActionsImageTiny = "contentActions_image--tiny"
        case contentActionsMinusMedium = "contentActions_minus--medium"
        case contentActionsMinusSmall = "contentActions_minus--small"
        case contentActionsPhoneCallMedium = "contentActions_phone-call--medium"
        case contentActionsPhoneCallSmall = "contentActions_phone-call--small"
        case contentActionsPhoneCallTiny = "contentActions_phone-call--tiny"
        case contentActionsPlusMedium = "contentActions_plus--medium"
        case contentActionsPlusSmall = "contentActions_plus--small"
        case contentActionsPreviewMedium = "contentActions_preview--medium"
        case contentActionsPreviewSmall = "contentActions_preview--small"
        case contentActionsPreviewCarouselMedium = "contentActions_preview-carousel--medium"
        case contentActionsPreviewCarouselSmall = "contentActions_preview-carousel--small"
        case contentActionsShareMedium = "contentActions_share--medium"
        case contentActionsShareSmall = "contentActions_share--small"
        case contentActionsShareAltMedium = "contentActions_share-alt--medium"
        case contentActionsShareAltSmall = "contentActions_share-alt--small"
        case contentActionsSortMedium = "contentActions_sort--medium"
        case contentActionsSortSmall = "contentActions_sort--small"
        case contentActionsSubtractMedium = "contentActions_subtract--medium"
        case contentActionsSubtractSmall = "contentActions_subtract--small"
        case contentActionsTrashMedium = "contentActions_trash--medium"
        case contentActionsTrashSmall = "contentActions_trash--small"
        case contentActionsUploadMedium = "contentActions_upload--medium"
        case contentActionsUploadSmall = "contentActions_upload--small"
        case contentActionsVideoMedium = "contentActions_video--medium"
        case contentActionsVideoSmall = "contentActions_video--small"
        case contentActionsVideoTiny = "contentActions_video--tiny"
        case contentModifierAvatarMedium = "contentModifier_avatar--medium"
        case contentModifierAvatarSmall = "contentModifier_avatar--small"
        case contentModifierAwardMedium = "contentModifier_award--medium"
        case contentModifierAwardSmall = "contentModifier_award--small"
        case contentModifierBackgroundCheckMedium = "contentModifier_background-check--medium"
        case contentModifierBackgroundCheckSmall = "contentModifier_background-check--small"
        case contentModifierBarGraphMedium = "contentModifier_bar-graph--medium"
        case contentModifierBarGraphSmall = "contentModifier_bar-graph--small"
        case contentModifierBusinessVerificationMedium = "contentModifier_business-verification--medium"
        case contentModifierBusinessVerificationSmall = "contentModifier_business-verification--small"
        case contentModifierCertifiedMedium = "contentModifier_certified--medium"
        case contentModifierCertifiedSmall = "contentModifier_certified--small"
        case contentModifierChartMedium = "contentModifier_chart--medium"
        case contentModifierChartSmall = "contentModifier_chart--small"
        case contentModifierCircleCheckMedium = "contentModifier_circle-check--medium"
        case contentModifierCircleCheckSmall = "contentModifier_circle-check--small"
        case contentModifierCircleCheckFilledMedium = "contentModifier_circle-check-filled--medium"
        case contentModifierCircleCheckFilledSmall = "contentModifier_circle-check-filled--small"
        case contentModifierCircleMapPinFilledMedium = "contentModifier_circle-map-pin-filled--medium"
        case contentModifierCircleMapPinFilledSmall = "contentModifier_circle-map-pin-filled--small"
        case contentModifierCircleMapPinFilledTiny = "contentModifier_circle-map-pin-filled--tiny"
        case contentModifierCircleMoneyFilledMedium = "contentModifier_circle-money-filled--medium"
        case contentModifierCircleMoneyFilledSmall = "contentModifier_circle-money-filled--small"
        case contentModifierCircleMoneyFilledTiny = "contentModifier_circle-money-filled--tiny"
        case contentModifierCreditCardMedium = "contentModifier_credit-card--medium"
        case contentModifierCreditCardSmall = "contentModifier_credit-card--small"
        case contentModifierDataMedium = "contentModifier_data--medium"
        case contentModifierDataSmall = "contentModifier_data--small"
        case contentModifierDatePlaceholderMedium = "contentModifier_date-placeholder--medium"
        case contentModifierDatePlaceholderSmall = "contentModifier_date-placeholder--small"
        case contentModifierDatePlaceholderTiny = "contentModifier_date-placeholder--tiny"
        case contentModifierDateTimeMedium = "contentModifier_date-time--medium"
        case contentModifierDateTimeSmall = "contentModifier_date-time--small"
        case contentModifierDocumentMedium = "contentModifier_document--medium"
        case contentModifierDocumentSmall = "contentModifier_document--small"
        case contentModifierDraftsMedium = "contentModifier_drafts--medium"
        case contentModifierDraftsSmall = "contentModifier_drafts--small"
        case contentModifierEnergyMedium = "contentModifier_energy--medium"
        case contentModifierFireMedium = "contentModifier_fire--medium"
        case contentModifierGiftMedium = "contentModifier_gift--medium"
        case contentModifierGiftSmall = "contentModifier_gift--small"
        case contentModifierGiftTiny = "contentModifier_gift--tiny"
        case contentModifierHeartRateMedium = "contentModifier_heart-rate--medium"
        case contentModifierLightbulbMedium = "contentModifier_lightbulb--medium"
        case contentModifierLightbulbSmall = "contentModifier_lightbulb--small"
        case contentModifierLightningMedium = "contentModifier_lightning--medium"
        case contentModifierLightningSmall = "contentModifier_lightning--small"
        case contentModifierLightningTiny = "contentModifier_lightning--tiny"
        case contentModifierListMedium = "contentModifier_list--medium"
        case contentModifierListSmall = "contentModifier_list--small"
        case contentModifierListTiny = "contentModifier_list--tiny"
        case contentModifierLocationMedium = "contentModifier_location--medium"
        case contentModifierLocationSmall = "contentModifier_location--small"
        case contentModifierLockedMedium = "contentModifier_locked--medium"
        case contentModifierLockedSmall = "contentModifier_locked--small"
        case contentModifierLockedTiny = "contentModifier_locked--tiny"
        case contentModifierMapMedium = "contentModifier_map--medium"
        case contentModifierMapSmall = "contentModifier_map--small"
        case contentModifierMapPinMedium = "contentModifier_map-pin--medium"
        case contentModifierMapPinSmall = "contentModifier_map-pin--small"
        case contentModifierMapPinTiny = "contentModifier_map-pin--tiny"
        case contentModifierMeetingConfirmedMedium = "contentModifier_meeting-confirmed--medium"
        case contentModifierMeetingConfirmedSmall = "contentModifier_meeting-confirmed--small"
        case contentModifierMeetingDeclinedMedium = "contentModifier_meeting-declined--medium"
        case contentModifierMeetingDeclinedSmall = "contentModifier_meeting-declined--small"
        case contentModifierMessageMedium = "contentModifier_message--medium"
        case contentModifierMessageSmall = "contentModifier_message--small"
        case contentModifierMessageTiny = "contentModifier_message--tiny"
        case contentModifierMessageDeclinedMedium = "contentModifier_message-declined--medium"
        case contentModifierMessageDeclinedSmall = "contentModifier_message-declined--small"
        case contentModifierMoldMedium = "contentModifier_mold--medium"
        case contentModifierMoneyMedium = "contentModifier_money--medium"
        case contentModifierMoneySmall = "contentModifier_money--small"
        case contentModifierMoneyTiny = "contentModifier_money--tiny"
        case contentModifierPeopleMedium = "contentModifier_people--medium"
        case contentModifierPeopleSmall = "contentModifier_people--small"
        case contentModifierPriceAssuranceTiny = "contentModifier_price-assurance--tiny"
        case contentModifierPriceTagMedium = "contentModifier_price-tag--medium"
        case contentModifierPriceTagSmall = "contentModifier_price-tag--small"
        case contentModifierPriceTagTiny = "contentModifier_price-tag--tiny"
        case contentModifierPriceTagFilledSmall = "contentModifier_price-tag-filled--small"
        case contentModifierRefundMedium = "contentModifier_refund--medium"
        case contentModifierRefundSmall = "contentModifier_refund--small"
        case contentModifierScheduleMeetingMedium = "contentModifier_schedule-meeting--medium"
        case contentModifierScheduleMeetingSmall = "contentModifier_schedule-meeting--small"
        case contentModifierSecurityMedium = "contentModifier_security--medium"
        case contentModifierSecurityTiny = "contentModifier_security--tiny"
        case contentModifierSentMedium = "contentModifier_sent--medium"
        case contentModifierSentSmall = "contentModifier_sent--small"
        case contentModifierSentFilledSmall = "contentModifier_sent-filled--small"
        case contentModifierServicesMedium = "contentModifier_services--medium"
        case contentModifierServicesSmall = "contentModifier_services--small"
        case contentModifierServicesFilledMedium = "contentModifier_services-filled--medium"
        case contentModifierTimeMedium = "contentModifier_time--medium"
        case contentModifierTimeSmall = "contentModifier_time--small"
        case contentModifierTrophyMedium = "contentModifier_trophy--medium"
        case contentModifierTrophySmall = "contentModifier_trophy--small"
        case contentModifierTrophyTiny = "contentModifier_trophy--tiny"
        case contentModifierUserMedium = "contentModifier_user--medium"
        case contentModifierUserSmall = "contentModifier_user--small"
        case contentModifierViewedMedium = "contentModifier_viewed--medium"
        case contentModifierViewedSmall = "contentModifier_viewed--small"
        case contentModifierWaterDropsMedium = "contentModifier_water-drops--medium"
        case contentModifierWavesMedium = "contentModifier_waves--medium"
        case contentModifierWebsiteMedium = "contentModifier_website--medium"
        case contentModifierWebsiteSmall = "contentModifier_website--small"
        case creditCardAmericanExpressMedium = "creditCard_american-express--medium"
        case creditCardDiscoverCardMedium = "creditCard_discover-card--medium"
        case creditCardMastercardMedium = "creditCard_mastercard--medium"
        case creditCardVisaMedium = "creditCard_visa--medium"
        case featureBookmarkMedium = "feature_bookmark--medium"
        case featureBookmarkSmall = "feature_bookmark--small"
        case featureCameraMedium = "feature_camera--medium"
        case featureCameraSmall = "feature_camera--small"
        case featureChatMedium = "feature_chat--medium"
        case featureChatSmall = "feature_chat--small"
        case featureExploreMedium = "feature_explore--medium"
        case featureExploreSmall = "feature_explore--small"
        case featureExploreFilledMedium = "feature_explore-filled--medium"
        case featureInboxMedium = "feature_inbox--medium"
        case featureInboxSmall = "feature_inbox--small"
        case featureInboxFilledMedium = "feature_inbox-filled--medium"
        case featureInboxFilledSmall = "feature_inbox-filled--small"
        case featureMailMedium = "feature_mail--medium"
        case featureMailSmall = "feature_mail--small"
        case featureMailFilledMedium = "feature_mail-filled--medium"
        case featureMessagesMedium = "feature_messages--medium"
        case featureMessagesSmall = "feature_messages--small"
        case featureMessagesFilledMedium = "feature_messages-filled--medium"
        case featureMessagesFilledSmall = "feature_messages-filled--small"
        case featurePortraitMedium = "feature_portrait--medium"
        case featurePortraitSmall = "feature_portrait--small"
        case featurePortraitFilledMedium = "feature_portrait-filled--medium"
        case featurePortraitFilledSmall = "feature_portrait-filled--small"
        case featurePreferencesMedium = "feature_preferences--medium"
        case featurePreferencesSmall = "feature_preferences--small"
        case featurePromotedMedium = "feature_promoted--medium"
        case featurePromotedSmall = "feature_promoted--small"
        case featurePromotedTiny = "feature_promoted--tiny"
        case featureStoreMedium = "feature_store--medium"
        case featureStoreFilledMedium = "feature_store-filled--medium"
        case inputsFavoriteMedium = "inputs_favorite--medium"
        case inputsFavoriteSmall = "inputs_favorite--small"
        case inputsFavoriteTiny = "inputs_favorite--tiny"
        case inputsFavoriteFilledMedium = "inputs_favorite-filled--medium"
        case inputsFavoriteFilledSmall = "inputs_favorite-filled--small"
        case inputsFavoriteFilledTiny = "inputs_favorite-filled--tiny"
        case inputsStarMedium = "inputs_star--medium"
        case inputsStarSmall = "inputs_star--small"
        case inputsStarTiny = "inputs_star--tiny"
        case inputsStarFilledMedium = "inputs_star-filled--medium"
        case inputsStarFilledSmall = "inputs_star-filled--small"
        case inputsStarFilledTiny = "inputs_star-filled--tiny"
        case inputsStarHalfFilledMedium = "inputs_star-half-filled--medium"
        case inputsStarHalfFilledSmall = "inputs_star-half-filled--small"
        case inputsStarHalfFilledTiny = "inputs_star-half-filled--tiny"
        case inputsThumbsDownMedium = "inputs_thumbs-down--medium"
        case inputsThumbsDownSmall = "inputs_thumbs-down--small"
        case inputsThumbsDownTiny = "inputs_thumbs-down--tiny"
        case inputsThumbsDownFilledMedium = "inputs_thumbs-down-filled--medium"
        case inputsThumbsDownFilledSmall = "inputs_thumbs-down-filled--small"
        case inputsThumbsDownFilledTiny = "inputs_thumbs-down-filled--tiny"
        case inputsThumbsUpMedium = "inputs_thumbs-up--medium"
        case inputsThumbsUpSmall = "inputs_thumbs-up--small"
        case inputsThumbsUpTiny = "inputs_thumbs-up--tiny"
        case inputsThumbsUpFilledMedium = "inputs_thumbs-up-filled--medium"
        case inputsThumbsUpFilledSmall = "inputs_thumbs-up-filled--small"
        case inputsThumbsUpFilledTiny = "inputs_thumbs-up-filled--tiny"
        case metaCategoryBusinessMedium = "metaCategory_business--medium"
        case metaCategoryBusinessSmall = "metaCategory_business--small"
        case metaCategoryCraftsMedium = "metaCategory_crafts--medium"
        case metaCategoryCraftsSmall = "metaCategory_crafts--small"
        case metaCategoryDesignWebMedium = "metaCategory_design-web--medium"
        case metaCategoryDesignWebSmall = "metaCategory_design-web--small"
        case metaCategoryEventsMedium = "metaCategory_events--medium"
        case metaCategoryEventsSmall = "metaCategory_events--small"
        case metaCategoryEventsTiny = "metaCategory_events--tiny"
        case metaCategoryHomeMedium = "metaCategory_home--medium"
        case metaCategoryHomeSmall = "metaCategory_home--small"
        case metaCategoryLegalMedium = "metaCategory_legal--medium"
        case metaCategoryLegalSmall = "metaCategory_legal--small"
        case metaCategoryLessonsMedium = "metaCategory_lessons--medium"
        case metaCategoryLessonsSmall = "metaCategory_lessons--small"
        case metaCategoryPersonalMedium = "metaCategory_personal--medium"
        case metaCategoryPersonalSmall = "metaCategory_personal--small"
        case metaCategoryPetsMedium = "metaCategory_pets--medium"
        case metaCategoryPetsSmall = "metaCategory_pets--small"
        case metaCategoryPhotographyMedium = "metaCategory_photography--medium"
        case metaCategoryPhotographySmall = "metaCategory_photography--small"
        case metaCategoryRepairSupportMedium = "metaCategory_repair-support--medium"
        case metaCategoryRepairSupportSmall = "metaCategory_repair-support--small"
        case metaCategoryWeddingMedium = "metaCategory_wedding--medium"
        case metaCategoryWeddingSmall = "metaCategory_wedding--small"
        case metaCategoryWellnessMedium = "metaCategory_wellness--medium"
        case metaCategoryWellnessSmall = "metaCategory_wellness--small"
        case metaCategoryWritingTranslationMedium = "metaCategory_writing-translation--medium"
        case metaCategoryWritingTranslationSmall = "metaCategory_writing-translation--small"
        case navigationArrowDownMedium = "navigation_arrow-down--medium"
        case navigationArrowDownSmall = "navigation_arrow-down--small"
        case navigationArrowDownTiny = "navigation_arrow-down--tiny"
        case navigationArrowLeftMedium = "navigation_arrow-left--medium"
        case navigationArrowLeftSmall = "navigation_arrow-left--small"
        case navigationArrowLeftTiny = "navigation_arrow-left--tiny"
        case navigationArrowRightMedium = "navigation_arrow-right--medium"
        case navigationArrowRightSmall = "navigation_arrow-right--small"
        case navigationArrowRightTiny = "navigation_arrow-right--tiny"
        case navigationArrowUpMedium = "navigation_arrow-up--medium"
        case navigationArrowUpSmall = "navigation_arrow-up--small"
        case navigationArrowUpTiny = "navigation_arrow-up--tiny"
        case navigationCaretDownMedium = "navigation_caret-down--medium"
        case navigationCaretDownSmall = "navigation_caret-down--small"
        case navigationCaretDownTiny = "navigation_caret-down--tiny"
        case navigationCaretLeftMedium = "navigation_caret-left--medium"
        case navigationCaretLeftSmall = "navigation_caret-left--small"
        case navigationCaretLeftTiny = "navigation_caret-left--tiny"
        case navigationCaretRightMedium = "navigation_caret-right--medium"
        case navigationCaretRightSmall = "navigation_caret-right--small"
        case navigationCaretRightTiny = "navigation_caret-right--tiny"
        case navigationCaretUpMedium = "navigation_caret-up--medium"
        case navigationCaretUpSmall = "navigation_caret-up--small"
        case navigationCaretUpTiny = "navigation_caret-up--tiny"
        case navigationCloseMedium = "navigation_close--medium"
        case navigationCloseSmall = "navigation_close--small"
        case navigationCloseTiny = "navigation_close--tiny"
        case navigationExpandMedium = "navigation_expand--medium"
        case navigationExpandSmall = "navigation_expand--small"
        case navigationFullscreenMedium = "navigation_fullscreen--medium"
        case navigationFullscreenSmall = "navigation_fullscreen--small"
        case navigationFullscreenCollapseMedium = "navigation_fullscreen-collapse--medium"
        case navigationFullscreenCollapseSmall = "navigation_fullscreen-collapse--small"
        case navigationHamburgerMedium = "navigation_hamburger--medium"
        case navigationHamburgerSmall = "navigation_hamburger--small"
        case navigationHomeMedium = "navigation_home--medium"
        case navigationHomeSmall = "navigation_home--small"
        case navigationMoreHorizontalMedium = "navigation_more-horizontal--medium"
        case navigationMoreHorizontalSmall = "navigation_more-horizontal--small"
        case navigationMoreVerticalMedium = "navigation_more-vertical--medium"
        case navigationMoreVerticalSmall = "navigation_more-vertical--small"
        case navigationPlayMedium = "navigation_play--medium"
        case navigationPlaySmall = "navigation_play--small"
        case navigationRefreshMedium = "navigation_refresh--medium"
        case navigationRefreshSmall = "navigation_refresh--small"
        case navigationReplyTiny = "navigation_reply--tiny"
        case navigationSearchMedium = "navigation_search--medium"
        case navigationSearchSmall = "navigation_search--small"
        case navigationSearchTiny = "navigation_search--tiny"
        case navigationSettingsMedium = "navigation_settings--medium"
        case navigationSettingsSmall = "navigation_settings--small"
        case navigationShrinkMedium = "navigation_shrink--medium"
        case navigationShrinkSmall = "navigation_shrink--small"
        case navigationSyncTiny = "navigation_sync--tiny"
        case notificationAlertsBlockedMedium = "notificationAlerts_blocked--medium"
        case notificationAlertsBlockedSmall = "notificationAlerts_blocked--small"
        case notificationAlertsBlockedFilledMedium = "notificationAlerts_blocked-filled--medium"
        case notificationAlertsBlockedFilledSmall = "notificationAlerts_blocked-filled--small"
        case notificationAlertsExclamationMedium = "notificationAlerts_exclamation--medium"
        case notificationAlertsExclamationSmall = "notificationAlerts_exclamation--small"
        case notificationAlertsHelpMedium = "notificationAlerts_help--medium"
        case notificationAlertsHelpSmall = "notificationAlerts_help--small"
        case notificationAlertsInfoMedium = "notificationAlerts_info--medium"
        case notificationAlertsInfoSmall = "notificationAlerts_info--small"
        case notificationAlertsInfoTiny = "notificationAlerts_info--tiny"
        case notificationAlertsInfoFilledMedium = "notificationAlerts_info-filled--medium"
        case notificationAlertsInfoFilledSmall = "notificationAlerts_info-filled--small"
        case notificationAlertsNotificationMedium = "notificationAlerts_notification--medium"
        case notificationAlertsNotificationSmall = "notificationAlerts_notification--small"
        case notificationAlertsNotificationFilledMedium = "notificationAlerts_notification-filled--medium"
        case notificationAlertsWarningMedium = "notificationAlerts_warning--medium"
        case notificationAlertsWarningSmall = "notificationAlerts_warning--small"
        case notificationAlertsWarningFilledMedium = "notificationAlerts_warning-filled--medium"
        case notificationAlertsWarningFilledSmall = "notificationAlerts_warning-filled--small"
        case socialAppleLoginMedium = "social_apple-login--medium"
        case socialFacebookMedium = "social_facebook--medium"
        case socialFacebookSmall = "social_facebook--small"
        case socialFacebookLoginMedium = "social_facebook-login--medium"
        case socialGoogleLoginMedium = "social_google-login--medium"
        case socialGoogleLoginSmall = "social_google-login--small"
        case socialGooglePlusMedium = "social_google-plus--medium"
        case socialGooglePlusSmall = "social_google-plus--small"
        case socialInstagramMedium = "social_instagram--medium"
        case socialInstagramSmall = "social_instagram--small"
        case socialMessengerMedium = "social_messenger--medium"
        case socialMessengerSmall = "social_messenger--small"
        case socialPinterestMedium = "social_pinterest--medium"
        case socialPinterestSmall = "social_pinterest--small"
        case socialTwitterMedium = "social_twitter--medium"
        case socialTwitterSmall = "social_twitter--small"
    }

    /// Dynamically get icon with the specified name (and size), if exists.
    ///
    /// Use of this function is typically discouraged since it creates a dependency
    /// on the file names used for icons that is not caught by the type checker.
    public static func icon(named name: String, size: Size? = nil) -> UIImage? {
        guard let size = size else {
            return UIImage(named: name, in: bundle, compatibleWith: nil)
        }

        let regex = ".*(\(Size.allCases.map(\.rawValue).joined(separator: "|")))$"
        guard !NSPredicate(format: "SELF MATCHES %@", regex).evaluate(with: name) else {
            return UIImage(named: name, in: bundle, compatibleWith: nil)
        }

        return UIImage(named: "\(name)\(size.rawValue)", in: bundle, compatibleWith: nil)
    }

    public static func icon(named name: Icon.Name) -> UIImage {
        requiredIcon(named: name.rawValue)
    }

    // MARK: - Private
    private static var bundle: Bundle! // swiftlint:disable:this implicitly_unwrapped_optional

    private static func requiredIcon(named name: String) -> UIImage {
        guard let icon = UIImage(named: name, in: bundle, compatibleWith: nil) else {
            assertionFailure("Expected bundle at path \(bundle?.bundlePath ?? "<missing>") to contain icon with name \(name).")
            return UIImage()
        }

        return icon
    }

    // MARK: Convenience Icon Accessors
    // ContentActions
    public static let contentActionsAddMedium = Self.requiredIcon(named: Self.Name.contentActionsAddMedium.rawValue)
    public static let contentActionsAddSmall = Self.requiredIcon(named: Self.Name.contentActionsAddSmall.rawValue)
    public static let contentActionsArchiveMedium = Self.requiredIcon(named: Self.Name.contentActionsArchiveMedium.rawValue)
    public static let contentActionsArchiveSmall = Self.requiredIcon(named: Self.Name.contentActionsArchiveSmall.rawValue)
    public static let contentActionsArchiveFilledSmall = Self.requiredIcon(named: Self.Name.contentActionsArchiveFilledSmall.rawValue)
    public static let contentActionsAttachMedium = Self.requiredIcon(named: Self.Name.contentActionsAttachMedium.rawValue)
    public static let contentActionsAttachSmall = Self.requiredIcon(named: Self.Name.contentActionsAttachSmall.rawValue)
    public static let contentActionsAttachTiny = Self.requiredIcon(named: Self.Name.contentActionsAttachTiny.rawValue)
    public static let contentActionsAudioMedium = Self.requiredIcon(named: Self.Name.contentActionsAudioMedium.rawValue)
    public static let contentActionsAudioSmall = Self.requiredIcon(named: Self.Name.contentActionsAudioSmall.rawValue)
    public static let contentActionsBudgetMedium = Self.requiredIcon(named: Self.Name.contentActionsBudgetMedium.rawValue)
    public static let contentActionsBudgetSmall = Self.requiredIcon(named: Self.Name.contentActionsBudgetSmall.rawValue)
    public static let contentActionsCheckMedium = Self.requiredIcon(named: Self.Name.contentActionsCheckMedium.rawValue)
    public static let contentActionsCheckSmall = Self.requiredIcon(named: Self.Name.contentActionsCheckSmall.rawValue)
    public static let contentActionsCheckTiny = Self.requiredIcon(named: Self.Name.contentActionsCheckTiny.rawValue)
    public static let contentActionsCopyLinkMedium = Self.requiredIcon(named: Self.Name.contentActionsCopyLinkMedium.rawValue)
    public static let contentActionsCopyLinkSmall = Self.requiredIcon(named: Self.Name.contentActionsCopyLinkSmall.rawValue)
    public static let contentActionsEditMedium = Self.requiredIcon(named: Self.Name.contentActionsEditMedium.rawValue)
    public static let contentActionsEditSmall = Self.requiredIcon(named: Self.Name.contentActionsEditSmall.rawValue)
    public static let contentActionsExportMedium = Self.requiredIcon(named: Self.Name.contentActionsExportMedium.rawValue)
    public static let contentActionsExportSmall = Self.requiredIcon(named: Self.Name.contentActionsExportSmall.rawValue)
    public static let contentActionsFilterMedium = Self.requiredIcon(named: Self.Name.contentActionsFilterMedium.rawValue)
    public static let contentActionsFilterSmall = Self.requiredIcon(named: Self.Name.contentActionsFilterSmall.rawValue)
    public static let contentActionsFlagMedium = Self.requiredIcon(named: Self.Name.contentActionsFlagMedium.rawValue)
    public static let contentActionsFlagSmall = Self.requiredIcon(named: Self.Name.contentActionsFlagSmall.rawValue)
    public static let contentActionsFolderMedium = Self.requiredIcon(named: Self.Name.contentActionsFolderMedium.rawValue)
    public static let contentActionsFolderSmall = Self.requiredIcon(named: Self.Name.contentActionsFolderSmall.rawValue)
    public static let contentActionsGestureMedium = Self.requiredIcon(named: Self.Name.contentActionsGestureMedium.rawValue)
    public static let contentActionsImageMedium = Self.requiredIcon(named: Self.Name.contentActionsImageMedium.rawValue)
    public static let contentActionsImageSmall = Self.requiredIcon(named: Self.Name.contentActionsImageSmall.rawValue)
    public static let contentActionsImageTiny = Self.requiredIcon(named: Self.Name.contentActionsImageTiny.rawValue)
    public static let contentActionsMinusMedium = Self.requiredIcon(named: Self.Name.contentActionsMinusMedium.rawValue)
    public static let contentActionsMinusSmall = Self.requiredIcon(named: Self.Name.contentActionsMinusSmall.rawValue)
    public static let contentActionsPhoneCallMedium = Self.requiredIcon(named: Self.Name.contentActionsPhoneCallMedium.rawValue)
    public static let contentActionsPhoneCallSmall = Self.requiredIcon(named: Self.Name.contentActionsPhoneCallSmall.rawValue)
    public static let contentActionsPhoneCallTiny = Self.requiredIcon(named: Self.Name.contentActionsPhoneCallTiny.rawValue)
    public static let contentActionsPlusMedium = Self.requiredIcon(named: Self.Name.contentActionsPlusMedium.rawValue)
    public static let contentActionsPlusSmall = Self.requiredIcon(named: Self.Name.contentActionsPlusSmall.rawValue)
    public static let contentActionsPreviewMedium = Self.requiredIcon(named: Self.Name.contentActionsPreviewMedium.rawValue)
    public static let contentActionsPreviewSmall = Self.requiredIcon(named: Self.Name.contentActionsPreviewSmall.rawValue)
    public static let contentActionsPreviewCarouselMedium = Self.requiredIcon(named: Self.Name.contentActionsPreviewCarouselMedium.rawValue)
    public static let contentActionsPreviewCarouselSmall = Self.requiredIcon(named: Self.Name.contentActionsPreviewCarouselSmall.rawValue)
    public static let contentActionsShareMedium = Self.requiredIcon(named: Self.Name.contentActionsShareMedium.rawValue)
    public static let contentActionsShareSmall = Self.requiredIcon(named: Self.Name.contentActionsShareSmall.rawValue)
    public static let contentActionsShareAltMedium = Self.requiredIcon(named: Self.Name.contentActionsShareAltMedium.rawValue)
    public static let contentActionsShareAltSmall = Self.requiredIcon(named: Self.Name.contentActionsShareAltSmall.rawValue)
    public static let contentActionsSortMedium = Self.requiredIcon(named: Self.Name.contentActionsSortMedium.rawValue)
    public static let contentActionsSortSmall = Self.requiredIcon(named: Self.Name.contentActionsSortSmall.rawValue)
    public static let contentActionsSubtractMedium = Self.requiredIcon(named: Self.Name.contentActionsSubtractMedium.rawValue)
    public static let contentActionsSubtractSmall = Self.requiredIcon(named: Self.Name.contentActionsSubtractSmall.rawValue)
    public static let contentActionsTrashMedium = Self.requiredIcon(named: Self.Name.contentActionsTrashMedium.rawValue)
    public static let contentActionsTrashSmall = Self.requiredIcon(named: Self.Name.contentActionsTrashSmall.rawValue)
    public static let contentActionsUploadMedium = Self.requiredIcon(named: Self.Name.contentActionsUploadMedium.rawValue)
    public static let contentActionsUploadSmall = Self.requiredIcon(named: Self.Name.contentActionsUploadSmall.rawValue)
    public static let contentActionsVideoMedium = Self.requiredIcon(named: Self.Name.contentActionsVideoMedium.rawValue)
    public static let contentActionsVideoSmall = Self.requiredIcon(named: Self.Name.contentActionsVideoSmall.rawValue)
    public static let contentActionsVideoTiny = Self.requiredIcon(named: Self.Name.contentActionsVideoTiny.rawValue)

    // ContentModifier
    public static let contentModifierAvatarMedium = Self.requiredIcon(named: Self.Name.contentModifierAvatarMedium.rawValue)
    public static let contentModifierAvatarSmall = Self.requiredIcon(named: Self.Name.contentModifierAvatarSmall.rawValue)
    public static let contentModifierAwardMedium = Self.requiredIcon(named: Self.Name.contentModifierAwardMedium.rawValue)
    public static let contentModifierAwardSmall = Self.requiredIcon(named: Self.Name.contentModifierAwardSmall.rawValue)
    public static let contentModifierBackgroundCheckMedium = Self.requiredIcon(named: Self.Name.contentModifierBackgroundCheckMedium.rawValue)
    public static let contentModifierBackgroundCheckSmall = Self.requiredIcon(named: Self.Name.contentModifierBackgroundCheckSmall.rawValue)
    public static let contentModifierBarGraphMedium = Self.requiredIcon(named: Self.Name.contentModifierBarGraphMedium.rawValue)
    public static let contentModifierBarGraphSmall = Self.requiredIcon(named: Self.Name.contentModifierBarGraphSmall.rawValue)
    public static let contentModifierBusinessVerificationMedium = Self.requiredIcon(named: Self.Name.contentModifierBusinessVerificationMedium.rawValue)
    public static let contentModifierBusinessVerificationSmall = Self.requiredIcon(named: Self.Name.contentModifierBusinessVerificationSmall.rawValue)
    public static let contentModifierCertifiedMedium = Self.requiredIcon(named: Self.Name.contentModifierCertifiedMedium.rawValue)
    public static let contentModifierCertifiedSmall = Self.requiredIcon(named: Self.Name.contentModifierCertifiedSmall.rawValue)
    public static let contentModifierChartMedium = Self.requiredIcon(named: Self.Name.contentModifierChartMedium.rawValue)
    public static let contentModifierChartSmall = Self.requiredIcon(named: Self.Name.contentModifierChartSmall.rawValue)
    public static let contentModifierCircleCheckMedium = Self.requiredIcon(named: Self.Name.contentModifierCircleCheckMedium.rawValue)
    public static let contentModifierCircleCheckSmall = Self.requiredIcon(named: Self.Name.contentModifierCircleCheckSmall.rawValue)
    public static let contentModifierCircleCheckFilledMedium = Self.requiredIcon(named: Self.Name.contentModifierCircleCheckFilledMedium.rawValue)
    public static let contentModifierCircleCheckFilledSmall = Self.requiredIcon(named: Self.Name.contentModifierCircleCheckFilledSmall.rawValue)
    public static let contentModifierCircleMapPinFilledMedium = Self.requiredIcon(named: Self.Name.contentModifierCircleMapPinFilledMedium.rawValue)
    public static let contentModifierCircleMapPinFilledSmall = Self.requiredIcon(named: Self.Name.contentModifierCircleMapPinFilledSmall.rawValue)
    public static let contentModifierCircleMapPinFilledTiny = Self.requiredIcon(named: Self.Name.contentModifierCircleMapPinFilledTiny.rawValue)
    public static let contentModifierCircleMoneyFilledMedium = Self.requiredIcon(named: Self.Name.contentModifierCircleMoneyFilledMedium.rawValue)
    public static let contentModifierCircleMoneyFilledSmall = Self.requiredIcon(named: Self.Name.contentModifierCircleMoneyFilledSmall.rawValue)
    public static let contentModifierCircleMoneyFilledTiny = Self.requiredIcon(named: Self.Name.contentModifierCircleMoneyFilledTiny.rawValue)
    public static let contentModifierCreditCardMedium = Self.requiredIcon(named: Self.Name.contentModifierCreditCardMedium.rawValue)
    public static let contentModifierCreditCardSmall = Self.requiredIcon(named: Self.Name.contentModifierCreditCardSmall.rawValue)
    public static let contentModifierDataMedium = Self.requiredIcon(named: Self.Name.contentModifierDataMedium.rawValue)
    public static let contentModifierDataSmall = Self.requiredIcon(named: Self.Name.contentModifierDataSmall.rawValue)
    public static let contentModifierDatePlaceholderMedium = Self.requiredIcon(named: Self.Name.contentModifierDatePlaceholderMedium.rawValue)
    public static let contentModifierDatePlaceholderSmall = Self.requiredIcon(named: Self.Name.contentModifierDatePlaceholderSmall.rawValue)
    public static let contentModifierDatePlaceholderTiny = Self.requiredIcon(named: Self.Name.contentModifierDatePlaceholderTiny.rawValue)
    public static let contentModifierDateTimeMedium = Self.requiredIcon(named: Self.Name.contentModifierDateTimeMedium.rawValue)
    public static let contentModifierDateTimeSmall = Self.requiredIcon(named: Self.Name.contentModifierDateTimeSmall.rawValue)
    public static let contentModifierDocumentMedium = Self.requiredIcon(named: Self.Name.contentModifierDocumentMedium.rawValue)
    public static let contentModifierDocumentSmall = Self.requiredIcon(named: Self.Name.contentModifierDocumentSmall.rawValue)
    public static let contentModifierDraftsMedium = Self.requiredIcon(named: Self.Name.contentModifierDraftsMedium.rawValue)
    public static let contentModifierDraftsSmall = Self.requiredIcon(named: Self.Name.contentModifierDraftsSmall.rawValue)
    public static let contentModifierEnergyMedium = Self.requiredIcon(named: Self.Name.contentModifierEnergyMedium.rawValue)
    public static let contentModifierFireMedium = Self.requiredIcon(named: Self.Name.contentModifierFireMedium.rawValue)
    public static let contentModifierGiftMedium = Self.requiredIcon(named: Self.Name.contentModifierGiftMedium.rawValue)
    public static let contentModifierGiftSmall = Self.requiredIcon(named: Self.Name.contentModifierGiftSmall.rawValue)
    public static let contentModifierGiftTiny = Self.requiredIcon(named: Self.Name.contentModifierGiftTiny.rawValue)
    public static let contentModifierHeartRateMedium = Self.requiredIcon(named: Self.Name.contentModifierHeartRateMedium.rawValue)
    public static let contentModifierLightbulbMedium = Self.requiredIcon(named: Self.Name.contentModifierLightbulbMedium.rawValue)
    public static let contentModifierLightbulbSmall = Self.requiredIcon(named: Self.Name.contentModifierLightbulbSmall.rawValue)
    public static let contentModifierLightningMedium = Self.requiredIcon(named: Self.Name.contentModifierLightningMedium.rawValue)
    public static let contentModifierLightningSmall = Self.requiredIcon(named: Self.Name.contentModifierLightningSmall.rawValue)
    public static let contentModifierLightningTiny = Self.requiredIcon(named: Self.Name.contentModifierLightningTiny.rawValue)
    public static let contentModifierListMedium = Self.requiredIcon(named: Self.Name.contentModifierListMedium.rawValue)
    public static let contentModifierListSmall = Self.requiredIcon(named: Self.Name.contentModifierListSmall.rawValue)
    public static let contentModifierListTiny = Self.requiredIcon(named: Self.Name.contentModifierListTiny.rawValue)
    public static let contentModifierLocationMedium = Self.requiredIcon(named: Self.Name.contentModifierLocationMedium.rawValue)
    public static let contentModifierLocationSmall = Self.requiredIcon(named: Self.Name.contentModifierLocationSmall.rawValue)
    public static let contentModifierLockedMedium = Self.requiredIcon(named: Self.Name.contentModifierLockedMedium.rawValue)
    public static let contentModifierLockedSmall = Self.requiredIcon(named: Self.Name.contentModifierLockedSmall.rawValue)
    public static let contentModifierLockedTiny = Self.requiredIcon(named: Self.Name.contentModifierLockedTiny.rawValue)
    public static let contentModifierMapMedium = Self.requiredIcon(named: Self.Name.contentModifierMapMedium.rawValue)
    public static let contentModifierMapSmall = Self.requiredIcon(named: Self.Name.contentModifierMapSmall.rawValue)
    public static let contentModifierMapPinMedium = Self.requiredIcon(named: Self.Name.contentModifierMapPinMedium.rawValue)
    public static let contentModifierMapPinSmall = Self.requiredIcon(named: Self.Name.contentModifierMapPinSmall.rawValue)
    public static let contentModifierMapPinTiny = Self.requiredIcon(named: Self.Name.contentModifierMapPinTiny.rawValue)
    public static let contentModifierMeetingConfirmedMedium = Self.requiredIcon(named: Self.Name.contentModifierMeetingConfirmedMedium.rawValue)
    public static let contentModifierMeetingConfirmedSmall = Self.requiredIcon(named: Self.Name.contentModifierMeetingConfirmedSmall.rawValue)
    public static let contentModifierMeetingDeclinedMedium = Self.requiredIcon(named: Self.Name.contentModifierMeetingDeclinedMedium.rawValue)
    public static let contentModifierMeetingDeclinedSmall = Self.requiredIcon(named: Self.Name.contentModifierMeetingDeclinedSmall.rawValue)
    public static let contentModifierMessageMedium = Self.requiredIcon(named: Self.Name.contentModifierMessageMedium.rawValue)
    public static let contentModifierMessageSmall = Self.requiredIcon(named: Self.Name.contentModifierMessageSmall.rawValue)
    public static let contentModifierMessageTiny = Self.requiredIcon(named: Self.Name.contentModifierMessageTiny.rawValue)
    public static let contentModifierMessageDeclinedMedium = Self.requiredIcon(named: Self.Name.contentModifierMessageDeclinedMedium.rawValue)
    public static let contentModifierMessageDeclinedSmall = Self.requiredIcon(named: Self.Name.contentModifierMessageDeclinedSmall.rawValue)
    public static let contentModifierMoldMedium = Self.requiredIcon(named: Self.Name.contentModifierMoldMedium.rawValue)
    public static let contentModifierMoneyMedium = Self.requiredIcon(named: Self.Name.contentModifierMoneyMedium.rawValue)
    public static let contentModifierMoneySmall = Self.requiredIcon(named: Self.Name.contentModifierMoneySmall.rawValue)
    public static let contentModifierMoneyTiny = Self.requiredIcon(named: Self.Name.contentModifierMoneyTiny.rawValue)
    public static let contentModifierPeopleMedium = Self.requiredIcon(named: Self.Name.contentModifierPeopleMedium.rawValue)
    public static let contentModifierPeopleSmall = Self.requiredIcon(named: Self.Name.contentModifierPeopleSmall.rawValue)
    public static let contentModifierPriceAssuranceTiny = Self.requiredIcon(named: Self.Name.contentModifierPriceAssuranceTiny.rawValue)
    public static let contentModifierPriceTagMedium = Self.requiredIcon(named: Self.Name.contentModifierPriceTagMedium.rawValue)
    public static let contentModifierPriceTagSmall = Self.requiredIcon(named: Self.Name.contentModifierPriceTagSmall.rawValue)
    public static let contentModifierPriceTagTiny = Self.requiredIcon(named: Self.Name.contentModifierPriceTagTiny.rawValue)
    public static let contentModifierPriceTagFilledSmall = Self.requiredIcon(named: Self.Name.contentModifierPriceTagFilledSmall.rawValue)
    public static let contentModifierRefundMedium = Self.requiredIcon(named: Self.Name.contentModifierRefundMedium.rawValue)
    public static let contentModifierRefundSmall = Self.requiredIcon(named: Self.Name.contentModifierRefundSmall.rawValue)
    public static let contentModifierScheduleMeetingMedium = Self.requiredIcon(named: Self.Name.contentModifierScheduleMeetingMedium.rawValue)
    public static let contentModifierScheduleMeetingSmall = Self.requiredIcon(named: Self.Name.contentModifierScheduleMeetingSmall.rawValue)
    public static let contentModifierSecurityMedium = Self.requiredIcon(named: Self.Name.contentModifierSecurityMedium.rawValue)
    public static let contentModifierSecurityTiny = Self.requiredIcon(named: Self.Name.contentModifierSecurityTiny.rawValue)
    public static let contentModifierSentMedium = Self.requiredIcon(named: Self.Name.contentModifierSentMedium.rawValue)
    public static let contentModifierSentSmall = Self.requiredIcon(named: Self.Name.contentModifierSentSmall.rawValue)
    public static let contentModifierSentFilledSmall = Self.requiredIcon(named: Self.Name.contentModifierSentFilledSmall.rawValue)
    public static let contentModifierServicesMedium = Self.requiredIcon(named: Self.Name.contentModifierServicesMedium.rawValue)
    public static let contentModifierServicesSmall = Self.requiredIcon(named: Self.Name.contentModifierServicesSmall.rawValue)
    public static let contentModifierServicesFilledMedium = Self.requiredIcon(named: Self.Name.contentModifierServicesFilledMedium.rawValue)
    public static let contentModifierTimeMedium = Self.requiredIcon(named: Self.Name.contentModifierTimeMedium.rawValue)
    public static let contentModifierTimeSmall = Self.requiredIcon(named: Self.Name.contentModifierTimeSmall.rawValue)
    public static let contentModifierTrophyMedium = Self.requiredIcon(named: Self.Name.contentModifierTrophyMedium.rawValue)
    public static let contentModifierTrophySmall = Self.requiredIcon(named: Self.Name.contentModifierTrophySmall.rawValue)
    public static let contentModifierTrophyTiny = Self.requiredIcon(named: Self.Name.contentModifierTrophyTiny.rawValue)
    public static let contentModifierUserMedium = Self.requiredIcon(named: Self.Name.contentModifierUserMedium.rawValue)
    public static let contentModifierUserSmall = Self.requiredIcon(named: Self.Name.contentModifierUserSmall.rawValue)
    public static let contentModifierViewedMedium = Self.requiredIcon(named: Self.Name.contentModifierViewedMedium.rawValue)
    public static let contentModifierViewedSmall = Self.requiredIcon(named: Self.Name.contentModifierViewedSmall.rawValue)
    public static let contentModifierWaterDropsMedium = Self.requiredIcon(named: Self.Name.contentModifierWaterDropsMedium.rawValue)
    public static let contentModifierWavesMedium = Self.requiredIcon(named: Self.Name.contentModifierWavesMedium.rawValue)
    public static let contentModifierWebsiteMedium = Self.requiredIcon(named: Self.Name.contentModifierWebsiteMedium.rawValue)
    public static let contentModifierWebsiteSmall = Self.requiredIcon(named: Self.Name.contentModifierWebsiteSmall.rawValue)

    // CreditCard
    public static let creditCardAmericanExpressMedium = Self.requiredIcon(named: Self.Name.creditCardAmericanExpressMedium.rawValue)
    public static let creditCardDiscoverCardMedium = Self.requiredIcon(named: Self.Name.creditCardDiscoverCardMedium.rawValue)
    public static let creditCardMastercardMedium = Self.requiredIcon(named: Self.Name.creditCardMastercardMedium.rawValue)
    public static let creditCardVisaMedium = Self.requiredIcon(named: Self.Name.creditCardVisaMedium.rawValue)

    // Feature
    public static let featureBookmarkMedium = Self.requiredIcon(named: Self.Name.featureBookmarkMedium.rawValue)
    public static let featureBookmarkSmall = Self.requiredIcon(named: Self.Name.featureBookmarkSmall.rawValue)
    public static let featureCameraMedium = Self.requiredIcon(named: Self.Name.featureCameraMedium.rawValue)
    public static let featureCameraSmall = Self.requiredIcon(named: Self.Name.featureCameraSmall.rawValue)
    public static let featureChatMedium = Self.requiredIcon(named: Self.Name.featureChatMedium.rawValue)
    public static let featureChatSmall = Self.requiredIcon(named: Self.Name.featureChatSmall.rawValue)
    public static let featureExploreMedium = Self.requiredIcon(named: Self.Name.featureExploreMedium.rawValue)
    public static let featureExploreSmall = Self.requiredIcon(named: Self.Name.featureExploreSmall.rawValue)
    public static let featureExploreFilledMedium = Self.requiredIcon(named: Self.Name.featureExploreFilledMedium.rawValue)
    public static let featureInboxMedium = Self.requiredIcon(named: Self.Name.featureInboxMedium.rawValue)
    public static let featureInboxSmall = Self.requiredIcon(named: Self.Name.featureInboxSmall.rawValue)
    public static let featureInboxFilledMedium = Self.requiredIcon(named: Self.Name.featureInboxFilledMedium.rawValue)
    public static let featureInboxFilledSmall = Self.requiredIcon(named: Self.Name.featureInboxFilledSmall.rawValue)
    public static let featureMailMedium = Self.requiredIcon(named: Self.Name.featureMailMedium.rawValue)
    public static let featureMailSmall = Self.requiredIcon(named: Self.Name.featureMailSmall.rawValue)
    public static let featureMailFilledMedium = Self.requiredIcon(named: Self.Name.featureMailFilledMedium.rawValue)
    public static let featureMessagesMedium = Self.requiredIcon(named: Self.Name.featureMessagesMedium.rawValue)
    public static let featureMessagesSmall = Self.requiredIcon(named: Self.Name.featureMessagesSmall.rawValue)
    public static let featureMessagesFilledMedium = Self.requiredIcon(named: Self.Name.featureMessagesFilledMedium.rawValue)
    public static let featureMessagesFilledSmall = Self.requiredIcon(named: Self.Name.featureMessagesFilledSmall.rawValue)
    public static let featurePortraitMedium = Self.requiredIcon(named: Self.Name.featurePortraitMedium.rawValue)
    public static let featurePortraitSmall = Self.requiredIcon(named: Self.Name.featurePortraitSmall.rawValue)
    public static let featurePortraitFilledMedium = Self.requiredIcon(named: Self.Name.featurePortraitFilledMedium.rawValue)
    public static let featurePortraitFilledSmall = Self.requiredIcon(named: Self.Name.featurePortraitFilledSmall.rawValue)
    public static let featurePreferencesMedium = Self.requiredIcon(named: Self.Name.featurePreferencesMedium.rawValue)
    public static let featurePreferencesSmall = Self.requiredIcon(named: Self.Name.featurePreferencesSmall.rawValue)
    public static let featurePromotedMedium = Self.requiredIcon(named: Self.Name.featurePromotedMedium.rawValue)
    public static let featurePromotedSmall = Self.requiredIcon(named: Self.Name.featurePromotedSmall.rawValue)
    public static let featurePromotedTiny = Self.requiredIcon(named: Self.Name.featurePromotedTiny.rawValue)
    public static let featureStoreMedium = Self.requiredIcon(named: Self.Name.featureStoreMedium.rawValue)
    public static let featureStoreFilledMedium = Self.requiredIcon(named: Self.Name.featureStoreFilledMedium.rawValue)

    // Inputs
    public static let inputsFavoriteMedium = Self.requiredIcon(named: Self.Name.inputsFavoriteMedium.rawValue)
    public static let inputsFavoriteSmall = Self.requiredIcon(named: Self.Name.inputsFavoriteSmall.rawValue)
    public static let inputsFavoriteTiny = Self.requiredIcon(named: Self.Name.inputsFavoriteTiny.rawValue)
    public static let inputsFavoriteFilledMedium = Self.requiredIcon(named: Self.Name.inputsFavoriteFilledMedium.rawValue)
    public static let inputsFavoriteFilledSmall = Self.requiredIcon(named: Self.Name.inputsFavoriteFilledSmall.rawValue)
    public static let inputsFavoriteFilledTiny = Self.requiredIcon(named: Self.Name.inputsFavoriteFilledTiny.rawValue)
    public static let inputsStarMedium = Self.requiredIcon(named: Self.Name.inputsStarMedium.rawValue)
    public static let inputsStarSmall = Self.requiredIcon(named: Self.Name.inputsStarSmall.rawValue)
    public static let inputsStarTiny = Self.requiredIcon(named: Self.Name.inputsStarTiny.rawValue)
    public static let inputsStarFilledMedium = Self.requiredIcon(named: Self.Name.inputsStarFilledMedium.rawValue)
    public static let inputsStarFilledSmall = Self.requiredIcon(named: Self.Name.inputsStarFilledSmall.rawValue)
    public static let inputsStarFilledTiny = Self.requiredIcon(named: Self.Name.inputsStarFilledTiny.rawValue)
    public static let inputsStarHalfFilledMedium = Self.requiredIcon(named: Self.Name.inputsStarHalfFilledMedium.rawValue)
    public static let inputsStarHalfFilledSmall = Self.requiredIcon(named: Self.Name.inputsStarHalfFilledSmall.rawValue)
    public static let inputsStarHalfFilledTiny = Self.requiredIcon(named: Self.Name.inputsStarHalfFilledTiny.rawValue)
    public static let inputsThumbsDownMedium = Self.requiredIcon(named: Self.Name.inputsThumbsDownMedium.rawValue)
    public static let inputsThumbsDownSmall = Self.requiredIcon(named: Self.Name.inputsThumbsDownSmall.rawValue)
    public static let inputsThumbsDownTiny = Self.requiredIcon(named: Self.Name.inputsThumbsDownTiny.rawValue)
    public static let inputsThumbsDownFilledMedium = Self.requiredIcon(named: Self.Name.inputsThumbsDownFilledMedium.rawValue)
    public static let inputsThumbsDownFilledSmall = Self.requiredIcon(named: Self.Name.inputsThumbsDownFilledSmall.rawValue)
    public static let inputsThumbsDownFilledTiny = Self.requiredIcon(named: Self.Name.inputsThumbsDownFilledTiny.rawValue)
    public static let inputsThumbsUpMedium = Self.requiredIcon(named: Self.Name.inputsThumbsUpMedium.rawValue)
    public static let inputsThumbsUpSmall = Self.requiredIcon(named: Self.Name.inputsThumbsUpSmall.rawValue)
    public static let inputsThumbsUpTiny = Self.requiredIcon(named: Self.Name.inputsThumbsUpTiny.rawValue)
    public static let inputsThumbsUpFilledMedium = Self.requiredIcon(named: Self.Name.inputsThumbsUpFilledMedium.rawValue)
    public static let inputsThumbsUpFilledSmall = Self.requiredIcon(named: Self.Name.inputsThumbsUpFilledSmall.rawValue)
    public static let inputsThumbsUpFilledTiny = Self.requiredIcon(named: Self.Name.inputsThumbsUpFilledTiny.rawValue)

    // MetaCategory
    public static let metaCategoryBusinessMedium = Self.requiredIcon(named: Self.Name.metaCategoryBusinessMedium.rawValue)
    public static let metaCategoryBusinessSmall = Self.requiredIcon(named: Self.Name.metaCategoryBusinessSmall.rawValue)
    public static let metaCategoryCraftsMedium = Self.requiredIcon(named: Self.Name.metaCategoryCraftsMedium.rawValue)
    public static let metaCategoryCraftsSmall = Self.requiredIcon(named: Self.Name.metaCategoryCraftsSmall.rawValue)
    public static let metaCategoryDesignWebMedium = Self.requiredIcon(named: Self.Name.metaCategoryDesignWebMedium.rawValue)
    public static let metaCategoryDesignWebSmall = Self.requiredIcon(named: Self.Name.metaCategoryDesignWebSmall.rawValue)
    public static let metaCategoryEventsMedium = Self.requiredIcon(named: Self.Name.metaCategoryEventsMedium.rawValue)
    public static let metaCategoryEventsSmall = Self.requiredIcon(named: Self.Name.metaCategoryEventsSmall.rawValue)
    public static let metaCategoryEventsTiny = Self.requiredIcon(named: Self.Name.metaCategoryEventsTiny.rawValue)
    public static let metaCategoryHomeMedium = Self.requiredIcon(named: Self.Name.metaCategoryHomeMedium.rawValue)
    public static let metaCategoryHomeSmall = Self.requiredIcon(named: Self.Name.metaCategoryHomeSmall.rawValue)
    public static let metaCategoryLegalMedium = Self.requiredIcon(named: Self.Name.metaCategoryLegalMedium.rawValue)
    public static let metaCategoryLegalSmall = Self.requiredIcon(named: Self.Name.metaCategoryLegalSmall.rawValue)
    public static let metaCategoryLessonsMedium = Self.requiredIcon(named: Self.Name.metaCategoryLessonsMedium.rawValue)
    public static let metaCategoryLessonsSmall = Self.requiredIcon(named: Self.Name.metaCategoryLessonsSmall.rawValue)
    public static let metaCategoryPersonalMedium = Self.requiredIcon(named: Self.Name.metaCategoryPersonalMedium.rawValue)
    public static let metaCategoryPersonalSmall = Self.requiredIcon(named: Self.Name.metaCategoryPersonalSmall.rawValue)
    public static let metaCategoryPetsMedium = Self.requiredIcon(named: Self.Name.metaCategoryPetsMedium.rawValue)
    public static let metaCategoryPetsSmall = Self.requiredIcon(named: Self.Name.metaCategoryPetsSmall.rawValue)
    public static let metaCategoryPhotographyMedium = Self.requiredIcon(named: Self.Name.metaCategoryPhotographyMedium.rawValue)
    public static let metaCategoryPhotographySmall = Self.requiredIcon(named: Self.Name.metaCategoryPhotographySmall.rawValue)
    public static let metaCategoryRepairSupportMedium = Self.requiredIcon(named: Self.Name.metaCategoryRepairSupportMedium.rawValue)
    public static let metaCategoryRepairSupportSmall = Self.requiredIcon(named: Self.Name.metaCategoryRepairSupportSmall.rawValue)
    public static let metaCategoryWeddingMedium = Self.requiredIcon(named: Self.Name.metaCategoryWeddingMedium.rawValue)
    public static let metaCategoryWeddingSmall = Self.requiredIcon(named: Self.Name.metaCategoryWeddingSmall.rawValue)
    public static let metaCategoryWellnessMedium = Self.requiredIcon(named: Self.Name.metaCategoryWellnessMedium.rawValue)
    public static let metaCategoryWellnessSmall = Self.requiredIcon(named: Self.Name.metaCategoryWellnessSmall.rawValue)
    public static let metaCategoryWritingTranslationMedium = Self.requiredIcon(named: Self.Name.metaCategoryWritingTranslationMedium.rawValue)
    public static let metaCategoryWritingTranslationSmall = Self.requiredIcon(named: Self.Name.metaCategoryWritingTranslationSmall.rawValue)

    // Navigation
    public static let navigationArrowDownMedium = Self.requiredIcon(named: Self.Name.navigationArrowDownMedium.rawValue)
    public static let navigationArrowDownSmall = Self.requiredIcon(named: Self.Name.navigationArrowDownSmall.rawValue)
    public static let navigationArrowDownTiny = Self.requiredIcon(named: Self.Name.navigationArrowDownTiny.rawValue)
    public static let navigationArrowLeftMedium = Self.requiredIcon(named: Self.Name.navigationArrowLeftMedium.rawValue)
    public static let navigationArrowLeftSmall = Self.requiredIcon(named: Self.Name.navigationArrowLeftSmall.rawValue)
    public static let navigationArrowLeftTiny = Self.requiredIcon(named: Self.Name.navigationArrowLeftTiny.rawValue)
    public static let navigationArrowRightMedium = Self.requiredIcon(named: Self.Name.navigationArrowRightMedium.rawValue)
    public static let navigationArrowRightSmall = Self.requiredIcon(named: Self.Name.navigationArrowRightSmall.rawValue)
    public static let navigationArrowRightTiny = Self.requiredIcon(named: Self.Name.navigationArrowRightTiny.rawValue)
    public static let navigationArrowUpMedium = Self.requiredIcon(named: Self.Name.navigationArrowUpMedium.rawValue)
    public static let navigationArrowUpSmall = Self.requiredIcon(named: Self.Name.navigationArrowUpSmall.rawValue)
    public static let navigationArrowUpTiny = Self.requiredIcon(named: Self.Name.navigationArrowUpTiny.rawValue)
    public static let navigationCaretDownMedium = Self.requiredIcon(named: Self.Name.navigationCaretDownMedium.rawValue)
    public static let navigationCaretDownSmall = Self.requiredIcon(named: Self.Name.navigationCaretDownSmall.rawValue)
    public static let navigationCaretDownTiny = Self.requiredIcon(named: Self.Name.navigationCaretDownTiny.rawValue)
    public static let navigationCaretLeftMedium = Self.requiredIcon(named: Self.Name.navigationCaretLeftMedium.rawValue)
    public static let navigationCaretLeftSmall = Self.requiredIcon(named: Self.Name.navigationCaretLeftSmall.rawValue)
    public static let navigationCaretLeftTiny = Self.requiredIcon(named: Self.Name.navigationCaretLeftTiny.rawValue)
    public static let navigationCaretRightMedium = Self.requiredIcon(named: Self.Name.navigationCaretRightMedium.rawValue)
    public static let navigationCaretRightSmall = Self.requiredIcon(named: Self.Name.navigationCaretRightSmall.rawValue)
    public static let navigationCaretRightTiny = Self.requiredIcon(named: Self.Name.navigationCaretRightTiny.rawValue)
    public static let navigationCaretUpMedium = Self.requiredIcon(named: Self.Name.navigationCaretUpMedium.rawValue)
    public static let navigationCaretUpSmall = Self.requiredIcon(named: Self.Name.navigationCaretUpSmall.rawValue)
    public static let navigationCaretUpTiny = Self.requiredIcon(named: Self.Name.navigationCaretUpTiny.rawValue)
    public static let navigationCloseMedium = Self.requiredIcon(named: Self.Name.navigationCloseMedium.rawValue)
    public static let navigationCloseSmall = Self.requiredIcon(named: Self.Name.navigationCloseSmall.rawValue)
    public static let navigationCloseTiny = Self.requiredIcon(named: Self.Name.navigationCloseTiny.rawValue)
    public static let navigationExpandMedium = Self.requiredIcon(named: Self.Name.navigationExpandMedium.rawValue)
    public static let navigationExpandSmall = Self.requiredIcon(named: Self.Name.navigationExpandSmall.rawValue)
    public static let navigationFullscreenMedium = Self.requiredIcon(named: Self.Name.navigationFullscreenMedium.rawValue)
    public static let navigationFullscreenSmall = Self.requiredIcon(named: Self.Name.navigationFullscreenSmall.rawValue)
    public static let navigationFullscreenCollapseMedium = Self.requiredIcon(named: Self.Name.navigationFullscreenCollapseMedium.rawValue)
    public static let navigationFullscreenCollapseSmall = Self.requiredIcon(named: Self.Name.navigationFullscreenCollapseSmall.rawValue)
    public static let navigationHamburgerMedium = Self.requiredIcon(named: Self.Name.navigationHamburgerMedium.rawValue)
    public static let navigationHamburgerSmall = Self.requiredIcon(named: Self.Name.navigationHamburgerSmall.rawValue)
    public static let navigationHomeMedium = Self.requiredIcon(named: Self.Name.navigationHomeMedium.rawValue)
    public static let navigationHomeSmall = Self.requiredIcon(named: Self.Name.navigationHomeSmall.rawValue)
    public static let navigationMoreHorizontalMedium = Self.requiredIcon(named: Self.Name.navigationMoreHorizontalMedium.rawValue)
    public static let navigationMoreHorizontalSmall = Self.requiredIcon(named: Self.Name.navigationMoreHorizontalSmall.rawValue)
    public static let navigationMoreVerticalMedium = Self.requiredIcon(named: Self.Name.navigationMoreVerticalMedium.rawValue)
    public static let navigationMoreVerticalSmall = Self.requiredIcon(named: Self.Name.navigationMoreVerticalSmall.rawValue)
    public static let navigationPlayMedium = Self.requiredIcon(named: Self.Name.navigationPlayMedium.rawValue)
    public static let navigationPlaySmall = Self.requiredIcon(named: Self.Name.navigationPlaySmall.rawValue)
    public static let navigationRefreshMedium = Self.requiredIcon(named: Self.Name.navigationRefreshMedium.rawValue)
    public static let navigationRefreshSmall = Self.requiredIcon(named: Self.Name.navigationRefreshSmall.rawValue)
    public static let navigationReplyTiny = Self.requiredIcon(named: Self.Name.navigationReplyTiny.rawValue)
    public static let navigationSearchMedium = Self.requiredIcon(named: Self.Name.navigationSearchMedium.rawValue)
    public static let navigationSearchSmall = Self.requiredIcon(named: Self.Name.navigationSearchSmall.rawValue)
    public static let navigationSearchTiny = Self.requiredIcon(named: Self.Name.navigationSearchTiny.rawValue)
    public static let navigationSettingsMedium = Self.requiredIcon(named: Self.Name.navigationSettingsMedium.rawValue)
    public static let navigationSettingsSmall = Self.requiredIcon(named: Self.Name.navigationSettingsSmall.rawValue)
    public static let navigationShrinkMedium = Self.requiredIcon(named: Self.Name.navigationShrinkMedium.rawValue)
    public static let navigationShrinkSmall = Self.requiredIcon(named: Self.Name.navigationShrinkSmall.rawValue)
    public static let navigationSyncTiny = Self.requiredIcon(named: Self.Name.navigationSyncTiny.rawValue)

    // Notification
    public static let notificationAlertsBlockedMedium = Self.requiredIcon(named: Self.Name.notificationAlertsBlockedMedium.rawValue)
    public static let notificationAlertsBlockedSmall = Self.requiredIcon(named: Self.Name.notificationAlertsBlockedSmall.rawValue)
    public static let notificationAlertsBlockedFilledMedium = Self.requiredIcon(named: Self.Name.notificationAlertsBlockedFilledMedium.rawValue)
    public static let notificationAlertsBlockedFilledSmall = Self.requiredIcon(named: Self.Name.notificationAlertsBlockedFilledSmall.rawValue)
    public static let notificationAlertsExclamationMedium = Self.requiredIcon(named: Self.Name.notificationAlertsExclamationMedium.rawValue)
    public static let notificationAlertsExclamationSmall = Self.requiredIcon(named: Self.Name.notificationAlertsExclamationSmall.rawValue)
    public static let notificationAlertsHelpMedium = Self.requiredIcon(named: Self.Name.notificationAlertsHelpMedium.rawValue)
    public static let notificationAlertsHelpSmall = Self.requiredIcon(named: Self.Name.notificationAlertsHelpSmall.rawValue)
    public static let notificationAlertsInfoMedium = Self.requiredIcon(named: Self.Name.notificationAlertsInfoMedium.rawValue)
    public static let notificationAlertsInfoSmall = Self.requiredIcon(named: Self.Name.notificationAlertsInfoSmall.rawValue)
    public static let notificationAlertsInfoTiny = Self.requiredIcon(named: Self.Name.notificationAlertsInfoTiny.rawValue)
    public static let notificationAlertsInfoFilledMedium = Self.requiredIcon(named: Self.Name.notificationAlertsInfoFilledMedium.rawValue)
    public static let notificationAlertsInfoFilledSmall = Self.requiredIcon(named: Self.Name.notificationAlertsInfoFilledSmall.rawValue)
    public static let notificationAlertsNotificationMedium = Self.requiredIcon(named: Self.Name.notificationAlertsNotificationMedium.rawValue)
    public static let notificationAlertsNotificationSmall = Self.requiredIcon(named: Self.Name.notificationAlertsNotificationSmall.rawValue)
    public static let notificationAlertsNotificationFilledMedium = Self.requiredIcon(named: Self.Name.notificationAlertsNotificationFilledMedium.rawValue)
    public static let notificationAlertsWarningMedium = Self.requiredIcon(named: Self.Name.notificationAlertsWarningMedium.rawValue)
    public static let notificationAlertsWarningSmall = Self.requiredIcon(named: Self.Name.notificationAlertsWarningSmall.rawValue)
    public static let notificationAlertsWarningFilledMedium = Self.requiredIcon(named: Self.Name.notificationAlertsWarningFilledMedium.rawValue)
    public static let notificationAlertsWarningFilledSmall = Self.requiredIcon(named: Self.Name.notificationAlertsWarningFilledSmall.rawValue)

    // Social
    public static let socialAppleLoginMedium = Self.requiredIcon(named: Self.Name.socialAppleLoginMedium.rawValue)
    public static let socialFacebookMedium = Self.requiredIcon(named: Self.Name.socialFacebookMedium.rawValue)
    public static let socialFacebookSmall = Self.requiredIcon(named: Self.Name.socialFacebookSmall.rawValue)
    public static let socialFacebookLoginMedium = Self.requiredIcon(named: Self.Name.socialFacebookLoginMedium.rawValue)
    public static let socialGoogleLoginMedium = Self.requiredIcon(named: Self.Name.socialGoogleLoginMedium.rawValue)
    public static let socialGoogleLoginSmall = Self.requiredIcon(named: Self.Name.socialGoogleLoginSmall.rawValue)
    public static let socialGooglePlusMedium = Self.requiredIcon(named: Self.Name.socialGooglePlusMedium.rawValue)
    public static let socialGooglePlusSmall = Self.requiredIcon(named: Self.Name.socialGooglePlusSmall.rawValue)
    public static let socialInstagramMedium = Self.requiredIcon(named: Self.Name.socialInstagramMedium.rawValue)
    public static let socialInstagramSmall = Self.requiredIcon(named: Self.Name.socialInstagramSmall.rawValue)
    public static let socialMessengerMedium = Self.requiredIcon(named: Self.Name.socialMessengerMedium.rawValue)
    public static let socialMessengerSmall = Self.requiredIcon(named: Self.Name.socialMessengerSmall.rawValue)
    public static let socialPinterestMedium = Self.requiredIcon(named: Self.Name.socialPinterestMedium.rawValue)
    public static let socialPinterestSmall = Self.requiredIcon(named: Self.Name.socialPinterestSmall.rawValue)
    public static let socialTwitterMedium = Self.requiredIcon(named: Self.Name.socialTwitterMedium.rawValue)
    public static let socialTwitterSmall = Self.requiredIcon(named: Self.Name.socialTwitterSmall.rawValue)

}
