import UIKit

public enum Icon {
    public enum Size: String, CaseIterable {
        case tiny = "--tiny"
        case small = "--small"
        case medium = "--medium"

        public var dimension: CGFloat {
            switch self {
            case .tiny:
                return 14
            case .small:
                return 18
            case .medium:
                return 28
            }
        }
    }

    /// *Must* be called before attempting to reference any icons.
    public static func register(bundle: Bundle) {
        Self.bundle = bundle
    }

    public static let contentActionsAddMedium = Self.requiredIcon(named: "add--medium")
    public static let contentActionsAddSmall = Self.requiredIcon(named: "add--small")
    public static let contentActionsArchiveMedium = Self.requiredIcon(named: "archive--medium")
    public static let contentActionsArchiveSmall = Self.requiredIcon(named: "archive--small")
    public static let contentActionsArchiveFilledSmall = Self.requiredIcon(named: "archive-filled--small")
    public static let contentActionsAttachMedium = Self.requiredIcon(named: "attach--medium")
    public static let contentActionsAttachSmall = Self.requiredIcon(named: "attach--small")
    public static let contentActionsAttachTiny = Self.requiredIcon(named: "attach--tiny")
    public static let contentActionsAudioMedium = Self.requiredIcon(named: "audio--medium")
    public static let contentActionsAudioSmall = Self.requiredIcon(named: "audio--small")
    public static let contentActionsBudgetMedium = Self.requiredIcon(named: "budget--medium")
    public static let contentActionsBudgetSmall = Self.requiredIcon(named: "budget--small")
    public static let contentActionsCheckMedium = Self.requiredIcon(named: "check--medium")
    public static let contentActionsCheckSmall = Self.requiredIcon(named: "check--small")
    public static let contentActionsCheckTiny = Self.requiredIcon(named: "check--tiny")
    public static let contentActionsCopyLinkMedium = Self.requiredIcon(named: "copy-link--medium")
    public static let contentActionsCopyLinkSmall = Self.requiredIcon(named: "copy-link--small")
    public static let contentActionsEditMedium = Self.requiredIcon(named: "edit--medium")
    public static let contentActionsEditSmall = Self.requiredIcon(named: "edit--small")
    public static let contentActionsExportMedium = Self.requiredIcon(named: "export--medium")
    public static let contentActionsExportSmall = Self.requiredIcon(named: "export--small")
    public static let contentActionsFilterMedium = Self.requiredIcon(named: "filter--medium")
    public static let contentActionsFilterSmall = Self.requiredIcon(named: "filter--small")
    public static let contentActionsFlagMedium = Self.requiredIcon(named: "flag--medium")
    public static let contentActionsFlagSmall = Self.requiredIcon(named: "flag--small")
    public static let contentActionsFolderMedium = Self.requiredIcon(named: "folder--medium")
    public static let contentActionsFolderSmall = Self.requiredIcon(named: "folder--small")
    public static let contentActionsGestureMedium = Self.requiredIcon(named: "gesture--medium")
    public static let contentActionsImageMedium = Self.requiredIcon(named: "image--medium")
    public static let contentActionsImageSmall = Self.requiredIcon(named: "image--small")
    public static let contentActionsImageTiny = Self.requiredIcon(named: "image--tiny")
    public static let contentActionsMinusMedium = Self.requiredIcon(named: "minus--medium")
    public static let contentActionsMinusSmall = Self.requiredIcon(named: "minus--small")
    public static let contentActionsPhoneCallMedium = Self.requiredIcon(named: "phone-call--medium")
    public static let contentActionsPhoneCallSmall = Self.requiredIcon(named: "phone-call--small")
    public static let contentActionsPhoneCallTiny = Self.requiredIcon(named: "phone-call--tiny")
    public static let contentActionsPlusMedium = Self.requiredIcon(named: "plus--medium")
    public static let contentActionsPlusSmall = Self.requiredIcon(named: "plus--small")
    public static let contentActionsPreviewMedium = Self.requiredIcon(named: "preview--medium")
    public static let contentActionsPreviewSmall = Self.requiredIcon(named: "preview--small")
    public static let contentActionsPreviewCarouselMedium = Self.requiredIcon(named: "preview-carousel--medium")
    public static let contentActionsPreviewCarouselSmall = Self.requiredIcon(named: "preview-carousel--small")
    public static let contentActionsShareMedium = Self.requiredIcon(named: "share--medium")
    public static let contentActionsShareSmall = Self.requiredIcon(named: "share--small")
    public static let contentActionsShareAltMedium = Self.requiredIcon(named: "share-alt--medium")
    public static let contentActionsShareAltSmall = Self.requiredIcon(named: "share-alt--small")
    public static let contentActionsSortMedium = Self.requiredIcon(named: "sort--medium")
    public static let contentActionsSortSmall = Self.requiredIcon(named: "sort--small")
    public static let contentActionsSubtractMedium = Self.requiredIcon(named: "subtract--medium")
    public static let contentActionsSubtractSmall = Self.requiredIcon(named: "subtract--small")
    public static let contentActionsTrashMedium = Self.requiredIcon(named: "trash--medium")
    public static let contentActionsTrashSmall = Self.requiredIcon(named: "trash--small")
    public static let contentActionsUploadMedium = Self.requiredIcon(named: "upload--medium")
    public static let contentActionsUploadSmall = Self.requiredIcon(named: "upload--small")
    public static let contentActionsVideoMedium = Self.requiredIcon(named: "video--medium")
    public static let contentActionsVideoSmall = Self.requiredIcon(named: "video--small")
    public static let contentActionsVideoTiny = Self.requiredIcon(named: "video--tiny")
    public static let contentModifierAvatarMedium = Self.requiredIcon(named: "avatar--medium")
    public static let contentModifierAvatarSmall = Self.requiredIcon(named: "avatar--small")
    public static let contentModifierAwardMedium = Self.requiredIcon(named: "award--medium")
    public static let contentModifierAwardSmall = Self.requiredIcon(named: "award--small")
    public static let contentModifierBackgroundCheckMedium = Self.requiredIcon(named: "background-check--medium")
    public static let contentModifierBackgroundCheckSmall = Self.requiredIcon(named: "background-check--small")
    public static let contentModifierBarGraphMedium = Self.requiredIcon(named: "bar-graph--medium")
    public static let contentModifierBarGraphSmall = Self.requiredIcon(named: "bar-graph--small")
    public static let contentModifierBusinessVerificationMedium = Self.requiredIcon(named: "business-verification--medium")
    public static let contentModifierBusinessVerificationSmall = Self.requiredIcon(named: "business-verification--small")
    public static let contentModifierCertifiedMedium = Self.requiredIcon(named: "certified--medium")
    public static let contentModifierCertifiedSmall = Self.requiredIcon(named: "certified--small")
    public static let contentModifierChartMedium = Self.requiredIcon(named: "chart--medium")
    public static let contentModifierChartSmall = Self.requiredIcon(named: "chart--small")
    public static let contentModifierCircleCheckMedium = Self.requiredIcon(named: "circle-check--medium")
    public static let contentModifierCircleCheckSmall = Self.requiredIcon(named: "circle-check--small")
    public static let contentModifierCircleCheckFilledMedium = Self.requiredIcon(named: "circle-check-filled--medium")
    public static let contentModifierCircleCheckFilledSmall = Self.requiredIcon(named: "circle-check-filled--small")
    public static let contentModifierCircleMapPinFilledMedium = Self.requiredIcon(named: "circle-map-pin-filled--medium")
    public static let contentModifierCircleMapPinFilledSmall = Self.requiredIcon(named: "circle-map-pin-filled--small")
    public static let contentModifierCircleMapPinFilledTiny = Self.requiredIcon(named: "circle-map-pin-filled--tiny")
    public static let contentModifierCircleMoneyFilledMedium = Self.requiredIcon(named: "circle-money-filled--medium")
    public static let contentModifierCircleMoneyFilledSmall = Self.requiredIcon(named: "circle-money-filled--small")
    public static let contentModifierCircleMoneyFilledTiny = Self.requiredIcon(named: "circle-money-filled--tiny")
    public static let contentModifierCreditCardMedium = Self.requiredIcon(named: "credit-card--medium")
    public static let contentModifierCreditCardSmall = Self.requiredIcon(named: "credit-card--small")
    public static let contentModifierDataMedium = Self.requiredIcon(named: "data--medium")
    public static let contentModifierDataSmall = Self.requiredIcon(named: "data--small")
    public static let contentModifierDatePlaceholderMedium = Self.requiredIcon(named: "date-placeholder--medium")
    public static let contentModifierDatePlaceholderSmall = Self.requiredIcon(named: "date-placeholder--small")
    public static let contentModifierDatePlaceholderTiny = Self.requiredIcon(named: "date-placeholder--tiny")
    public static let contentModifierDateTimeMedium = Self.requiredIcon(named: "date-time--medium")
    public static let contentModifierDateTimeSmall = Self.requiredIcon(named: "date-time--small")
    public static let contentModifierDocumentMedium = Self.requiredIcon(named: "document--medium")
    public static let contentModifierDocumentSmall = Self.requiredIcon(named: "document--small")
    public static let contentModifierDraftsMedium = Self.requiredIcon(named: "drafts--medium")
    public static let contentModifierDraftsSmall = Self.requiredIcon(named: "drafts--small")
    public static let contentModifierEnergyMedium = Self.requiredIcon(named: "energy--medium")
    public static let contentModifierFireMedium = Self.requiredIcon(named: "fire--medium")
    public static let contentModifierGiftMedium = Self.requiredIcon(named: "gift--medium")
    public static let contentModifierGiftSmall = Self.requiredIcon(named: "gift--small")
    public static let contentModifierGiftTiny = Self.requiredIcon(named: "gift--tiny")
    public static let contentModifierHeartRateMedium = Self.requiredIcon(named: "heart-rate--medium")
    public static let contentModifierLightbulbMedium = Self.requiredIcon(named: "lightbulb--medium")
    public static let contentModifierLightbulbSmall = Self.requiredIcon(named: "lightbulb--small")
    public static let contentModifierLightningMedium = Self.requiredIcon(named: "lightning--medium")
    public static let contentModifierLightningSmall = Self.requiredIcon(named: "lightning--small")
    public static let contentModifierLightningTiny = Self.requiredIcon(named: "lightning--tiny")
    public static let contentModifierListMedium = Self.requiredIcon(named: "list--medium")
    public static let contentModifierListSmall = Self.requiredIcon(named: "list--small")
    public static let contentModifierLocationMedium = Self.requiredIcon(named: "location--medium")
    public static let contentModifierLocationSmall = Self.requiredIcon(named: "location--small")
    public static let contentModifierLockedMedium = Self.requiredIcon(named: "locked--medium")
    public static let contentModifierLockedSmall = Self.requiredIcon(named: "locked--small")
    public static let contentModifierLockedTiny = Self.requiredIcon(named: "locked--tiny")
    public static let contentModifierMapMedium = Self.requiredIcon(named: "map--medium")
    public static let contentModifierMapSmall = Self.requiredIcon(named: "map--small")
    public static let contentModifierMapPinMedium = Self.requiredIcon(named: "map-pin--medium")
    public static let contentModifierMapPinSmall = Self.requiredIcon(named: "map-pin--small")
    public static let contentModifierMapPinTiny = Self.requiredIcon(named: "map-pin--tiny")
    public static let contentModifierMeetingConfirmedMedium = Self.requiredIcon(named: "meeting-confirmed--medium")
    public static let contentModifierMeetingConfirmedSmall = Self.requiredIcon(named: "meeting-confirmed--small")
    public static let contentModifierMeetingDeclinedMedium = Self.requiredIcon(named: "meeting-declined--medium")
    public static let contentModifierMeetingDeclinedSmall = Self.requiredIcon(named: "meeting-declined--small")
    public static let contentModifierMessageMedium = Self.requiredIcon(named: "message--medium")
    public static let contentModifierMessageSmall = Self.requiredIcon(named: "message--small")
    public static let contentModifierMessageTiny = Self.requiredIcon(named: "message--tiny")
    public static let contentModifierMessageDeclinedMedium = Self.requiredIcon(named: "message-declined--medium")
    public static let contentModifierMessageDeclinedSmall = Self.requiredIcon(named: "message-declined--small")
    public static let contentModifierMoldMedium = Self.requiredIcon(named: "mold--medium")
    public static let contentModifierMoneyMedium = Self.requiredIcon(named: "money--medium")
    public static let contentModifierMoneySmall = Self.requiredIcon(named: "money--small")
    public static let contentModifierMoneyTiny = Self.requiredIcon(named: "money--tiny")
    public static let contentModifierPeopleMedium = Self.requiredIcon(named: "people--medium")
    public static let contentModifierPeopleSmall = Self.requiredIcon(named: "people--small")
    public static let contentModifierPriceAssuranceTiny = Self.requiredIcon(named: "price-assurance--tiny")
    public static let contentModifierPriceTagMedium = Self.requiredIcon(named: "price-tag--medium")
    public static let contentModifierPriceTagSmall = Self.requiredIcon(named: "price-tag--small")
    public static let contentModifierPriceTagTiny = Self.requiredIcon(named: "price-tag--tiny")
    public static let contentModifierPriceTagFilledSmall = Self.requiredIcon(named: "price-tag-filled--small")
    public static let contentModifierRefundMedium = Self.requiredIcon(named: "refund--medium")
    public static let contentModifierRefundSmall = Self.requiredIcon(named: "refund--small")
    public static let contentModifierScheduleMeetingMedium = Self.requiredIcon(named: "schedule-meeting--medium")
    public static let contentModifierScheduleMeetingSmall = Self.requiredIcon(named: "schedule-meeting--small")
    public static let contentModifierSecurityMedium = Self.requiredIcon(named: "security--medium")
    public static let contentModifierSecurityTiny = Self.requiredIcon(named: "security--tiny")
    public static let contentModifierSentMedium = Self.requiredIcon(named: "sent--medium")
    public static let contentModifierSentSmall = Self.requiredIcon(named: "sent--small")
    public static let contentModifierSentFilledSmall = Self.requiredIcon(named: "sent-filled--small")
    public static let contentModifierServicesMedium = Self.requiredIcon(named: "services--medium")
    public static let contentModifierServicesSmall = Self.requiredIcon(named: "services--small")
    public static let contentModifierServicesFilledMedium = Self.requiredIcon(named: "services-filled--medium")
    public static let contentModifierTimeMedium = Self.requiredIcon(named: "time--medium")
    public static let contentModifierTimeSmall = Self.requiredIcon(named: "time--small")
    public static let contentModifierTrophyMedium = Self.requiredIcon(named: "trophy--medium")
    public static let contentModifierTrophySmall = Self.requiredIcon(named: "trophy--small")
    public static let contentModifierTrophyTiny = Self.requiredIcon(named: "trophy--tiny")
    public static let contentModifierUserMedium = Self.requiredIcon(named: "user--medium")
    public static let contentModifierUserSmall = Self.requiredIcon(named: "user--small")
    public static let contentModifierViewedMedium = Self.requiredIcon(named: "viewed--medium")
    public static let contentModifierViewedSmall = Self.requiredIcon(named: "viewed--small")
    public static let contentModifierWaterDropsMedium = Self.requiredIcon(named: "water-drops--medium")
    public static let contentModifierWavesMedium = Self.requiredIcon(named: "waves--medium")
    public static let contentModifierWebsiteMedium = Self.requiredIcon(named: "website--medium")
    public static let contentModifierWebsiteSmall = Self.requiredIcon(named: "website--small")
    public static let creditCardAmericanExpressMedium = Self.requiredIcon(named: "american-express--medium")
    public static let creditCardDiscoverCardMedium = Self.requiredIcon(named: "discover-card--medium")
    public static let creditCardMastercardMedium = Self.requiredIcon(named: "mastercard--medium")
    public static let creditCardVisaMedium = Self.requiredIcon(named: "visa--medium")
    public static let featureBookmarkMedium = Self.requiredIcon(named: "bookmark--medium")
    public static let featureBookmarkSmall = Self.requiredIcon(named: "bookmark--small")
    public static let featureCameraMedium = Self.requiredIcon(named: "camera--medium")
    public static let featureCameraSmall = Self.requiredIcon(named: "camera--small")
    public static let featureChatMedium = Self.requiredIcon(named: "chat--medium")
    public static let featureChatSmall = Self.requiredIcon(named: "chat--small")
    public static let featureExploreMedium = Self.requiredIcon(named: "explore--medium")
    public static let featureExploreSmall = Self.requiredIcon(named: "explore--small")
    public static let featureExploreFilledMedium = Self.requiredIcon(named: "explore-filled--medium")
    public static let featureInboxMedium = Self.requiredIcon(named: "inbox--medium")
    public static let featureInboxSmall = Self.requiredIcon(named: "inbox--small")
    public static let featureInboxFilledMedium = Self.requiredIcon(named: "inbox-filled--medium")
    public static let featureInboxFilledSmall = Self.requiredIcon(named: "inbox-filled--small")
    public static let featureMailMedium = Self.requiredIcon(named: "mail--medium")
    public static let featureMailSmall = Self.requiredIcon(named: "mail--small")
    public static let featureMailFilledMedium = Self.requiredIcon(named: "mail-filled--medium")
    public static let featureMessagesMedium = Self.requiredIcon(named: "messages--medium")
    public static let featureMessagesSmall = Self.requiredIcon(named: "messages--small")
    public static let featureMessagesFilledMedium = Self.requiredIcon(named: "messages-filled--medium")
    public static let featureMessagesFilledSmall = Self.requiredIcon(named: "messages-filled--small")
    public static let featurePortraitMedium = Self.requiredIcon(named: "portrait--medium")
    public static let featurePortraitSmall = Self.requiredIcon(named: "portrait--small")
    public static let featurePortraitFilledMedium = Self.requiredIcon(named: "portrait-filled--medium")
    public static let featurePortraitFilledSmall = Self.requiredIcon(named: "portrait-filled--small")
    public static let featurePreferencesMedium = Self.requiredIcon(named: "preferences--medium")
    public static let featurePreferencesSmall = Self.requiredIcon(named: "preferences--small")
    public static let featurePromotedMedium = Self.requiredIcon(named: "promoted--medium")
    public static let featurePromotedSmall = Self.requiredIcon(named: "promoted--small")
    public static let featurePromotedTiny = Self.requiredIcon(named: "promoted--tiny")
    public static let featureStoreMedium = Self.requiredIcon(named: "store--medium")
    public static let featureStoreFilledMedium = Self.requiredIcon(named: "store-filled--medium")
    public static let inputsFavoriteMedium = Self.requiredIcon(named: "favorite--medium")
    public static let inputsFavoriteSmall = Self.requiredIcon(named: "favorite--small")
    public static let inputsFavoriteTiny = Self.requiredIcon(named: "favorite--tiny")
    public static let inputsFavoriteFilledMedium = Self.requiredIcon(named: "favorite-filled--medium")
    public static let inputsFavoriteFilledSmall = Self.requiredIcon(named: "favorite-filled--small")
    public static let inputsFavoriteFilledTiny = Self.requiredIcon(named: "favorite-filled--tiny")
    public static let inputsStarMedium = Self.requiredIcon(named: "star--medium")
    public static let inputsStarSmall = Self.requiredIcon(named: "star--small")
    public static let inputsStarTiny = Self.requiredIcon(named: "star--tiny")
    public static let inputsStarFilledMedium = Self.requiredIcon(named: "star-filled--medium")
    public static let inputsStarFilledSmall = Self.requiredIcon(named: "star-filled--small")
    public static let inputsStarFilledTiny = Self.requiredIcon(named: "star-filled--tiny")
    public static let inputsStarHalfFilledMedium = Self.requiredIcon(named: "star-half-filled--medium")
    public static let inputsStarHalfFilledSmall = Self.requiredIcon(named: "star-half-filled--small")
    public static let inputsStarHalfFilledTiny = Self.requiredIcon(named: "star-half-filled--tiny")
    public static let inputsThumbsDownMedium = Self.requiredIcon(named: "thumbs-down--medium")
    public static let inputsThumbsDownSmall = Self.requiredIcon(named: "thumbs-down--small")
    public static let inputsThumbsDownTiny = Self.requiredIcon(named: "thumbs-down--tiny")
    public static let inputsThumbsDownFilledMedium = Self.requiredIcon(named: "thumbs-down-filled--medium")
    public static let inputsThumbsDownFilledSmall = Self.requiredIcon(named: "thumbs-down-filled--small")
    public static let inputsThumbsDownFilledTiny = Self.requiredIcon(named: "thumbs-down-filled--tiny")
    public static let inputsThumbsUpMedium = Self.requiredIcon(named: "thumbs-up--medium")
    public static let inputsThumbsUpSmall = Self.requiredIcon(named: "thumbs-up--small")
    public static let inputsThumbsUpTiny = Self.requiredIcon(named: "thumbs-up--tiny")
    public static let inputsThumbsUpFilledMedium = Self.requiredIcon(named: "thumbs-up-filled--medium")
    public static let inputsThumbsUpFilledSmall = Self.requiredIcon(named: "thumbs-up-filled--small")
    public static let inputsThumbsUpFilledTiny = Self.requiredIcon(named: "thumbs-up-filled--tiny")
    public static let metaCategoryBusinessMedium = Self.requiredIcon(named: "business--medium")
    public static let metaCategoryBusinessSmall = Self.requiredIcon(named: "business--small")
    public static let metaCategoryCraftsMedium = Self.requiredIcon(named: "crafts--medium")
    public static let metaCategoryCraftsSmall = Self.requiredIcon(named: "crafts--small")
    public static let metaCategoryDesignWebMedium = Self.requiredIcon(named: "design-web--medium")
    public static let metaCategoryDesignWebSmall = Self.requiredIcon(named: "design-web--small")
    public static let metaCategoryEventsMedium = Self.requiredIcon(named: "events--medium")
    public static let metaCategoryEventsSmall = Self.requiredIcon(named: "events--small")
    public static let metaCategoryEventsTiny = Self.requiredIcon(named: "events--tiny")
    public static let metaCategoryHomeMedium = Self.requiredIcon(named: "home--medium")
    public static let metaCategoryHomeSmall = Self.requiredIcon(named: "home--small")
    public static let metaCategoryLegalMedium = Self.requiredIcon(named: "legal--medium")
    public static let metaCategoryLegalSmall = Self.requiredIcon(named: "legal--small")
    public static let metaCategoryLessonsMedium = Self.requiredIcon(named: "lessons--medium")
    public static let metaCategoryLessonsSmall = Self.requiredIcon(named: "lessons--small")
    public static let metaCategoryPersonalMedium = Self.requiredIcon(named: "personal--medium")
    public static let metaCategoryPersonalSmall = Self.requiredIcon(named: "personal--small")
    public static let metaCategoryPetsMedium = Self.requiredIcon(named: "pets--medium")
    public static let metaCategoryPetsSmall = Self.requiredIcon(named: "pets--small")
    public static let metaCategoryPhotographyMedium = Self.requiredIcon(named: "photography--medium")
    public static let metaCategoryPhotographySmall = Self.requiredIcon(named: "photography--small")
    public static let metaCategoryRepairSupportMedium = Self.requiredIcon(named: "repair-support--medium")
    public static let metaCategoryRepairSupportSmall = Self.requiredIcon(named: "repair-support--small")
    public static let metaCategoryWeddingMedium = Self.requiredIcon(named: "wedding--medium")
    public static let metaCategoryWeddingSmall = Self.requiredIcon(named: "wedding--small")
    public static let metaCategoryWellnessMedium = Self.requiredIcon(named: "wellness--medium")
    public static let metaCategoryWellnessSmall = Self.requiredIcon(named: "wellness--small")
    public static let metaCategoryWritingTranslationMedium = Self.requiredIcon(named: "writing-translation--medium")
    public static let metaCategoryWritingTranslationSmall = Self.requiredIcon(named: "writing-translation--small")
    public static let navigationArrowDownMedium = Self.requiredIcon(named: "navigation/arrow-down--medium")
    public static let navigationArrowDownSmall = Self.requiredIcon(named: "navigation/arrow-down--small")
    public static let navigationArrowDownTiny = Self.requiredIcon(named: "navigation/arrow-down--tiny")
    public static let navigationArrowLeftMedium = Self.requiredIcon(named: "navigation/arrow-left--medium")
    public static let navigationArrowLeftSmall = Self.requiredIcon(named: "navigation/arrow-left--small")
    public static let navigationArrowLeftTiny = Self.requiredIcon(named: "navigation/arrow-left--tiny")
    public static let navigationArrowRightMedium = Self.requiredIcon(named: "navigation/arrow-right--medium")
    public static let navigationArrowRightSmall = Self.requiredIcon(named: "navigation/arrow-right--small")
    public static let navigationArrowRightTiny = Self.requiredIcon(named: "navigation/arrow-right--tiny")
    public static let navigationArrowUpMedium = Self.requiredIcon(named: "navigation/arrow-up--medium")
    public static let navigationArrowUpSmall = Self.requiredIcon(named: "navigation/arrow-up--small")
    public static let navigationArrowUpTiny = Self.requiredIcon(named: "navigation/arrow-up--tiny")
    public static let navigationCaretDownMedium = Self.requiredIcon(named: "navigation/caret-down--medium")
    public static let navigationCaretDownSmall = Self.requiredIcon(named: "navigation/caret-down--small")
    public static let navigationCaretDownTiny = Self.requiredIcon(named: "navigation/caret-down--tiny")
    public static let navigationCaretLeftMedium = Self.requiredIcon(named: "navigation/caret-left--medium")
    public static let navigationCaretLeftSmall = Self.requiredIcon(named: "navigation/caret-left--small")
    public static let navigationCaretLeftTiny = Self.requiredIcon(named: "navigation/caret-left--tiny")
    public static let navigationCaretRightMedium = Self.requiredIcon(named: "navigation/caret-right--medium")
    public static let navigationCaretRightSmall = Self.requiredIcon(named: "navigation/caret-right--small")
    public static let navigationCaretRightTiny = Self.requiredIcon(named: "navigation/caret-right--tiny")
    public static let navigationCaretUpMedium = Self.requiredIcon(named: "navigation/caret-up--medium")
    public static let navigationCaretUpSmall = Self.requiredIcon(named: "navigation/caret-up--small")
    public static let navigationCaretUpTiny = Self.requiredIcon(named: "navigation/caret-up--tiny")
    public static let navigationCloseMedium = Self.requiredIcon(named: "navigation/close--medium")
    public static let navigationCloseSmall = Self.requiredIcon(named: "navigation/close--small")
    public static let navigationCloseTiny = Self.requiredIcon(named: "navigation/close--tiny")
    public static let navigationExpandMedium = Self.requiredIcon(named: "navigation/expand--medium")
    public static let navigationExpandSmall = Self.requiredIcon(named: "navigation/expand--small")
    public static let navigationFullscreenMedium = Self.requiredIcon(named: "navigation/fullscreen--medium")
    public static let navigationFullscreenSmall = Self.requiredIcon(named: "navigation/fullscreen--small")
    public static let navigationFullscreenCollapseMedium = Self.requiredIcon(named: "navigation/fullscreen-collapse--medium")
    public static let navigationFullscreenCollapseSmall = Self.requiredIcon(named: "navigation/fullscreen-collapse--small")
    public static let navigationHamburgerMedium = Self.requiredIcon(named: "navigation/hamburger--medium")
    public static let navigationHamburgerSmall = Self.requiredIcon(named: "navigation/hamburger--small")
    public static let navigationHomeMedium = Self.requiredIcon(named: "navigation/home--medium")
    public static let navigationHomeSmall = Self.requiredIcon(named: "navigation/home--small")
    public static let navigationMoreHorizontalMedium = Self.requiredIcon(named: "navigation/more-horizontal--medium")
    public static let navigationMoreHorizontalSmall = Self.requiredIcon(named: "navigation/more-horizontal--small")
    public static let navigationMoreVerticalMedium = Self.requiredIcon(named: "navigation/more-vertical--medium")
    public static let navigationMoreVerticalSmall = Self.requiredIcon(named: "navigation/more-vertical--small")
    public static let navigationPlayMedium = Self.requiredIcon(named: "navigation/play--medium")
    public static let navigationPlaySmall = Self.requiredIcon(named: "navigation/play--small")
    public static let navigationRefreshMedium = Self.requiredIcon(named: "navigation/refresh--medium")
    public static let navigationRefreshSmall = Self.requiredIcon(named: "navigation/refresh--small")
    public static let navigationReplyTiny = Self.requiredIcon(named: "navigation/reply--tiny")
    public static let navigationSearchMedium = Self.requiredIcon(named: "navigation/search--medium")
    public static let navigationSearchSmall = Self.requiredIcon(named: "navigation/search--small")
    public static let navigationSearchTiny = Self.requiredIcon(named: "navigation/search--tiny")
    public static let navigationSettingsMedium = Self.requiredIcon(named: "navigation/settings--medium")
    public static let navigationSettingsSmall = Self.requiredIcon(named: "navigation/settings--small")
    public static let navigationShrinkMedium = Self.requiredIcon(named: "navigation/shrink--medium")
    public static let navigationShrinkSmall = Self.requiredIcon(named: "navigation/shrink--small")
    public static let navigationSyncTiny = Self.requiredIcon(named: "navigation/sync--tiny")
    public static let notificationAlertsBlockedMedium = Self.requiredIcon(named: "notificationAlerts/blocked--medium")
    public static let notificationAlertsBlockedSmall = Self.requiredIcon(named: "notificationAlerts/blocked--small")
    public static let notificationAlertsBlockedFilledMedium = Self.requiredIcon(named: "notificationAlerts/blocked-filled--medium")
    public static let notificationAlertsBlockedFilledSmall = Self.requiredIcon(named: "notificationAlerts/blocked-filled--small")
    public static let notificationAlertsExclamationMedium = Self.requiredIcon(named: "notificationAlerts/exclamation--medium")
    public static let notificationAlertsExclamationSmall = Self.requiredIcon(named: "notificationAlerts/exclamation--small")
    public static let notificationAlertsHelpMedium = Self.requiredIcon(named: "notificationAlerts/help--medium")
    public static let notificationAlertsHelpSmall = Self.requiredIcon(named: "notificationAlerts/help--small")
    public static let notificationAlertsInfoMedium = Self.requiredIcon(named: "notificationAlerts/info--medium")
    public static let notificationAlertsInfoSmall = Self.requiredIcon(named: "notificationAlerts/info--small")
    public static let notificationAlertsInfoTiny = Self.requiredIcon(named: "notificationAlerts/info--tiny")
    public static let notificationAlertsInfoFilledMedium = Self.requiredIcon(named: "notificationAlerts/info-filled--medium")
    public static let notificationAlertsInfoFilledSmall = Self.requiredIcon(named: "notificationAlerts/info-filled--small")
    public static let notificationAlertsNotificationMedium = Self.requiredIcon(named: "notificationAlerts/notification--medium")
    public static let notificationAlertsNotificationSmall = Self.requiredIcon(named: "notificationAlerts/notification--small")
    public static let notificationAlertsNotificationFilledMedium = Self.requiredIcon(named: "notificationAlerts/notification-filled--medium")
    public static let notificationAlertsWarningMedium = Self.requiredIcon(named: "notificationAlerts/warning--medium")
    public static let notificationAlertsWarningSmall = Self.requiredIcon(named: "notificationAlerts/warning--small")
    public static let notificationAlertsWarningFilledMedium = Self.requiredIcon(named: "notificationAlerts/warning-filled--medium")
    public static let notificationAlertsWarningFilledSmall = Self.requiredIcon(named: "notificationAlerts/warning-filled--small")
    public static let socialAppleLoginMedium = Self.requiredIcon(named: "apple-login--medium")
    public static let socialFacebookMedium = Self.requiredIcon(named: "facebook--medium")
    public static let socialFacebookSmall = Self.requiredIcon(named: "facebook--small")
    public static let socialFacebookLoginMedium = Self.requiredIcon(named: "facebook-login--medium")
    public static let socialGoogleLoginMedium = Self.requiredIcon(named: "google-login--medium")
    public static let socialGoogleLoginSmall = Self.requiredIcon(named: "google-login--small")
    public static let socialGooglePlusMedium = Self.requiredIcon(named: "google-plus--medium")
    public static let socialGooglePlusSmall = Self.requiredIcon(named: "google-plus--small")
    public static let socialInstagramMedium = Self.requiredIcon(named: "instagram--medium")
    public static let socialInstagramSmall = Self.requiredIcon(named: "instagram--small")
    public static let socialMessengerMedium = Self.requiredIcon(named: "messenger--medium")
    public static let socialMessengerSmall = Self.requiredIcon(named: "messenger--small")
    public static let socialPinterestMedium = Self.requiredIcon(named: "pinterest--medium")
    public static let socialPinterestSmall = Self.requiredIcon(named: "pinterest--small")
    public static let socialTwitterMedium = Self.requiredIcon(named: "twitter--medium")
    public static let socialTwitterSmall = Self.requiredIcon(named: "twitter--small")

    /// Dynamically get icon with the specified name (and size), if exists.
    ///
    /// Use of this function is typically discouraged since it creates a dependency
    /// on the file names used for icons that is not caught by the type checker.
    public static func icon(named name: String, size: Size? = nil) -> UIImage? {
        guard let size = size else {
            return UIImage(named: name, in: bundle, compatibleWith: nil)
        }

        let regex = ".*(\(Size.allCases.map(\.rawValue).joined(separator: "|")))$"
        guard !NSPredicate(format: "SELF MATCHES %@", regex).evaluate(with: name) else {
            return UIImage(named: name, in: bundle, compatibleWith: nil)
        }

        return UIImage(named: "\(name)\(size.rawValue)", in: bundle, compatibleWith: nil)
    }

    // MARK: - Private
    private static var bundle: Bundle! // swiftlint:disable:this implicitly_unwrapped_optional

    private static func requiredIcon(named name: String) -> UIImage {
        guard let icon = UIImage(named: name, in: bundle, compatibleWith: nil) else {
            assertionFailure("Expected bundle at path \(bundle?.bundlePath ?? "<missing>") to contain icon with name \(name).")
            return UIImage()
        }

        return icon
    }
}
